<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$_config = $this->helper('Sm\Market\Helper\Data');
?>

<div class="footer-container footer-style-8">
	<div class="footer-wrapper">
		
		<div class="footer-top-container">
			<div class="container">
				<div class="footer-top">
					<div class="row">
						<div class="col-md-3 col-sm-6 col-xs-12 contact-footer">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-footer')->toHtml(); ?>
						</div>
						
						<div class="col-md-3 col-sm-6 col-xs-12 about-store">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about-footer')->toHtml(); ?>
						</div>
						
						<div class="col-md-3 col-sm-6 col-xs-12 customer-services">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('customer-services-footer')->toHtml(); ?>
						</div>
						
						<div class="col-md-3 col-sm-6 col-xs-12 newsletter-footer">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter-footer')->toHtml(); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-middle">
			<div class="container">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-middle-content')->toHtml(); ?>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-7 col-sm-7 copyright-footer">
						<?php if($_config->getAdvanced('custom_copyright')){ ?>
							<address><?php echo $_config->getAdvanced('copyright_content') ?></address>
						<?php } else {?>
							<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
						<?php } ?>
					</div>
					
					<div class="col-lg-6 col-md-5 col-sm-5 payment-footer">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft7-payment')->toHtml(); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<?php if($_config->getAdvanced('show_gototop')){ ?>
		<a id="yt-totop" href="javascript:void(0)" title="Go to Top"></a>
	<?php } ?>
	
</div>




