<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>

<?php
	$_config = $this->helper('Sm\Market\Helper\Data');
	$locale = $_config->getLocale();
	
	$full_path =  dirname(__FILE__);
	$arr_full_path = explode('app',$full_path);
	$root_path = '/';
	if(isset($arr_full_path[0])) $root_path = $arr_full_path[0];
	$root_path .= 'apps/magento/htdocs/'; // Surender - 04/01/2017 - Fix for windows

	//Absolute Path
	$nav_mobile_path = $root_path.'pub/static/frontend/Sm/market/'.$locale.'/Magento_Theme/nav-mobile.html';
	
	if(!file_exists($nav_mobile_path)){
		$columnsLimit = $block->getColumnsLimit() ?: 0;
		$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
		
		//Due to css issue, need to add <nav> & <ul> tag in the beginning & end
		$_menu = '<nav class="navigation-mobile"><ul>' . $_menu . '</ul></nav> ' . PHP_EOL;
		$_menu .= "<script type=\"text/javascript\">".PHP_EOL;
		$_menu .= "require(['jquery'], function ($) {".PHP_EOL;
		//$_menu .= "	$('.navigation-mobile > ul li').has('ul').append( '<span class=\"touch-button\"><span>open</span></span>' );".PHP_EOL;
		$_menu .= "});</script>".PHP_EOL;
		file_put_contents($nav_mobile_path,$_menu);
	}
	//path from url. changes each time static-content is deployed
	$url_static = $_config->getUrlStatic();
	$nav_mobile_file = $url_static . 'frontend/Sm/market/'.$locale.'/Magento_Theme/nav-mobile.html';
?>

<!--COLLAPSE-->
<?php if($_config->getGeneral('responsive_menu') == 'collapse'){?>
	<div class="nav-mobile-container collapse-type">
		<div class="btn-mobile">
			<a id="collapse-button" class="button-mobile collapse-nav" title="<?php echo __('Categories')?>"><i class="fa fa-bars"></i><span class="hidden"><?php echo __('Categories')?></span></a>
		</div>
		
		<div art-include-html="<?php /* @escapeNotVerified */ echo $nav_mobile_file ?>"></div>
		
		
	</div>
<?php } ?>

<!--SIDEBAR-->
<?php if($_config->getGeneral('responsive_menu') == 'sidebar'){?>
	<div class="nav-mobile-container sidebar-type">
		<div class="btn-mobile">
			<a id="sidebar-button" class="button-mobile sidebar-nav" title="<?php echo __('Categories')?>"><i class="fa fa-bars"></i><span class="hidden"><?php echo __('Categories')?></span></a>
		</div>
		
		<div art-include-html="<?php /* @escapeNotVerified */ echo $nav_mobile_file ?>">
		<!--NAV MOBILE / CSS MENU-->
		<script type="text/javascript">art.includeHTML();</script>
		<script type="text/javascript">
			require([
				'jquery'
			], function ($) {
				<?php if($_config->getGeneral('responsive_menu') == 'sidebar'){ ?>
				$('#sidebar-button').click(function(){
					$('body').toggleClass('navbar-active');
					$(this).toggleClass('active');
				});
				<?php }else{ ?>
				$('#collapse-button').click(function(){
					$('.navigation-mobile').slideToggle(200);
					$(this).toggleClass('active');
				});
				<?php } ?>
				$('.navigation-mobile > ul li').has('ul').append( '<span class="touch-button"><span>open</span></span>' );
				$('.touch-button').click(function(){
					$(this).prev().slideToggle(200);
					$(this).toggleClass('active');
					$(this).parent().toggleClass('parent-active');
				});
			});
		</script>
		</div>
		
	</div>
<?php } ?>
