<?php
/*------------------------------------------------------------------------
# SM Market - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

namespace Sm\Market\Model\Config\Source;

class ListGoogleFont implements \Magento\Framework\Option\ArrayInterface
{
	public function toOptionArray()
	{
		return [
			['value' => 'Aclonica', 'label' => __('Aclonica')],
			['value' => 'Allan', 'label' => __('Allan')],
			['value' => 'Anonymous+Pro', 'label' => __('Anonymous Pro')],
			['value' => 'Allerta+Stencil', 'label' => __('Allerta Stencil')],
			['value' => 'Allerta', 'label' => __('Allerta')],
			['value' => 'Amaranth', 'label' => __('Amaranth')],
			['value' => 'Anton', 'label' => __('Anton')],
			['value' => 'Arimo', 'label' => __('Arimo')],
			['value' => 'Artifika', 'label' => __('Artifika')],
			['value' => 'Arvo', 'label' => __('Arvo')],
			['value' => 'Asset', 'label' => __('Asset')],
			['value' => 'Astloch', 'label' => __('Astloch')],
			['value' => 'Bangers', 'label' => __('Bangers')],
			['value' => 'Bentham', 'label' => __('Bentham')],
			['value' => 'Bevan', 'label' => __('Bevan')],
			['value' => 'Bigshot+One', 'label' => __('Bigshot One')],
			['value' => 'Bowlby+One', 'label' => __('Bowlby One')],
			['value' => 'Brawler', 'label' => __('Brawler ')],
			['value' => 'Buda:300', 'label' => __('Buda')],
			['value' => 'Cabin', 'label' => __('Cabin')],
			['value' => 'Calligraffitti', 'label' => __('Calligraffitti')],
			['value' => 'Candal', 'label' => __('Candal')],
			['value' => 'Cantarell', 'label' => __('Cantarell')],
			['value' => 'Cardo', 'label' => __('Cardo')],
			['value' => 'Carter One', 'label' => __('Carter One')],
			['value' => 'Caudex', 'label' => __('Caudex')],
			['value' => 'Chewy', 'label' => __('Chewy')],
			['value' => 'Coda', 'label' => __('Coda')],
			['value' => 'Coming+Soon', 'label' => __('Coming Soon')],
			['value' => 'Copse', 'label' => __('Copse')],
			['value' => 'Corben:700', 'label' => __('Corben')],
			['value' => 'Cousine', 'label' => __('Cousine')],
			['value' => 'Crafty+Girls', 'label' => __('Crafty Girls')],
			['value' => 'Crimson+Text', 'label' => __('Crimson Text')],
			['value' => 'Crushed', 'label' => __('Crushed')],
			['value' => 'Cuprum', 'label' => __('Cuprum')],
			['value' => 'Damion', 'label' => __('Damion')],
			['value' => 'Dancing+Script', 'label' => __('Dancing Script')],
			['value' => 'Didact+Gothic', 'label' => __('Didact Gothic')],
			['value' => 'Droid+Sans', 'label' => __('Droid Sans')],
			['value' => 'Droid+Sans:400', 'label' => __('Droid Sans 400')],
			['value' => 'Droid+Sans:700', 'label' => __('Droid Sans 700')],
			['value' => 'Droid+Serif', 'label' => __('Droid Serif')],
			['value' => 'Dosis', 'label' => __('Dosis')],
			['value' => 'Dosis:500', 'label' => __('Dosis 500')],
			['value' => 'Dosis:700', 'label' => __('Dosis 700')],
			['value' => 'Dosis:800', 'label' => __('Dosis 800')],
			['value' => 'EB+Garamond', 'label' => __('EB Garamond')],
			['value' => 'Expletus+Sans', 'label' => __('Expletus Sans')],
			['value' => 'Forum', 'label' => __('Forum')],
			['value' => 'Francois+One', 'label' => __('Francois One')],
			['value' => 'Geo', 'label' => __('Geo')],
			['value' => 'Goblin+One', 'label' => __('Goblin One')],
			['value' => 'Gravitas+One', 'label' => __('Gravitas One')],
			['value' => 'Gruppo', 'label' => __('Gruppo')],
			['value' => 'Inconsolata', 'label' => __('Inconsolata')],
			['value' => 'Indie+Flower', 'label' => __('Indie Flower')],
			['value' => 'Irish+Grover', 'label' => __('Irish Grover')],
			['value' => 'Irish+Growler', 'label' => __('Irish Growler')],
			['value' => 'Istok+Web', 'label' => __('Istok Web')],
			['value' => 'Judson', 'label' => __('Judson')],
			['value' => 'Jura', 'label' => __(' Jura Regular')],
			['value' => 'Jura:500', 'label' => __(' Jura 500')],
			['value' => 'Jura:600', 'label' => __(' Jura 600')],
			['value' => 'Kameron', 'label' => __('Kameron')],
			['value' => 'Kenia', 'label' => __('Kenia')],
			['value' => 'Kranky', 'label' => __('Kranky')],
			['value' => 'Kreon', 'label' => __('Kreon')],
			['value' => 'Kristi', 'label' => __('Kristi')],
			['value' => 'Lato:100', 'label' => __('Lato 100')],
			['value' => 'Lato', 'label' => __('Lato')],
			['value' => 'Lato:900', 'label' => __('Lato 900')],
			['value' => 'League+Script', 'label' => __('League Script')],
			['value' => 'Lekton', 'label' => __(' Lekton ')],
			['value' => 'Limelight', 'label' => __(' Limelight ')],
			['value' => 'Lobster', 'label' => __('Lobster')],
			['value' => 'Lobster+Two', 'label' => __('Lobster Two')],
			['value' => 'Lora', 'label' => __('Lora')],
			['value' => 'Luckiest+Guy', 'label' => __('Luckiest Guy')],
			['value' => 'Maiden+Orange', 'label' => __('Maiden Orange')],
			['value' => 'Mako', 'label' => __('Mako')],
			['value' => 'Maven+Pro', 'label' => __(' Maven Pro')],
			['value' => 'Maven+Pro:500', 'label' => __(' Maven Pro 500')],
			['value' => 'Maven+Pro:700', 'label' => __(' Maven Pro 700')],
			['value' => 'Maven+Pro:900', 'label' => __(' Maven Pro 900')],
			['value' => 'Meddon', 'label' => __('Meddon')],
			['value' => 'MedievalSharp', 'label' => __('MedievalSharp')],
			['value' => 'Megrim', 'label' => __('Megrim')],
			['value' => 'Merriweather', 'label' => __('Merriweather')],
			['value' => 'Metrophobic', 'label' => __('Metrophobic')],
			['value' => 'Michroma', 'label' => __('Michroma')],
			['value' => 'Miltonian', 'label' => __('Miltonian')],
			['value' => 'Modern Antiqua', 'label' => __('Modern Antiqua')],
			['value' => 'Monofett', 'label' => __('Monofett')],
			['value' => 'Molengo', 'label' => __('Molengo')],
			['value' => 'Muli:300', 'label' => __('Muli Light')],
			['value' => 'Muli', 'label' => __('Muli Regular')],
			['value' => 'Neucha', 'label' => __('Neucha')],
			['value' => 'Neuton', 'label' => __('Neuton')],
			['value' => 'News+Cycle', 'label' => __('News Cycle')],
			['value' => 'Nixie+One', 'label' => __('Nixie One')],
			['value' => 'Nobile', 'label' => __('Nobile')],
			['value' => 'Nova+Cut', 'label' => __('Nova Cut')],
			['value' => 'Nova+Flat', 'label' => __('Nova Flat')],
			['value' => 'Nova+Mono', 'label' => __('Nova Mono')],
			['value' => 'Nova+Oval', 'label' => __('Nova Oval')],
			['value' => 'Nova+Round', 'label' => __('Nova Round')],
			['value' => 'Nova+Script', 'label' => __('Nova Script')],
			['value' => 'Nova+Slim', 'label' => __('Nova Slim')],
			['value' => 'Nova+Square', 'label' => __('Nova Square')],
			['value' => 'Nunito:light', 'label' => __(' Nunito Light')],
			['value' => 'Nunito', 'label' => __(' Nunito Regular')],
			['value' => 'Oswald', 'label' => __('Oswald')],
			['value' => 'Open+Sans:400,600,700', 'label' => __('Open Sans')],
			['value' => 'Open+Sans:400italic', 'label' => __('Open Sans 400 Italic')],
			['value' => 'Open+Sans:700', 'label' => __('Open Sans 700')],
			['value' => 'Open+Sans+Condensed:300', 'label' => __('Open Sans Condensed 300')],
			['value' => 'Open+Sans+Condensed:300italic', 'label' => __('Open Sans Condensed 300 Italic')],
			['value' => 'Open+Sans+Condensed:700', 'label' => __('Open Sans Condensed 700')],
			['value' => 'Reenie+Beanie', 'label' => __('Reenie Beanie')],
			['value' => 'Pacifico', 'label' => __('Pacifico')],
			['value' => 'Patrick+Hand', 'label' => __('Patrick Hand')],
			['value' => 'Paytone+One', 'label' => __('Paytone One')],
			['value' => 'Philosopher', 'label' => __('Philosopher')],
			['value' => 'Play', 'label' => __('Play')],
			['value' => 'Podkova', 'label' => __(' Podkova ')],
			['value' => 'PT+Sans', 'label' => __('PT Sans')],
			['value' => 'PT+Serif', 'label' => __('PT Serif')],
			['value' => 'Puritan', 'label' => __('Puritan')],
			['value' => 'Poppins:300,400,500,600,700', 'label' => __('Poppins')],
			['value' => 'Quattrocento', 'label' => __('Quattrocento')],
			['value' => 'Radley', 'label' => __('Radley')],
			['value' => 'Raleway:100', 'label' => __('Raleway')],
			['value' => 'Redressed', 'label' => __('Redressed')],
			['value' => 'Roboto+Condensed:300', 'label' => __(' Roboto Condensed 300')],
			['value' => 'Roboto+Condensed:400', 'label' => __(' Roboto Condensed 400')],
			['value' => 'Roboto+Condensed:700', 'label' => __(' Roboto Condensed 700')],
			['value' => 'Rock+Salt', 'label' => __('Rock Salt')],
			['value' => 'Rokkitt', 'label' => __('Rokkitt')],
			['value' => 'Schoolbell', 'label' => __('Schoolbell')],
			['value' => 'Shanti', 'label' => __('Shanti')],
			['value' => 'Sigmar+One', 'label' => __('Sigmar One')],
			['value' => 'Six+Caps', 'label' => __('Six Caps')],
			['value' => 'Slackey', 'label' => __('Slackey')],
			['value' => 'Smythe', 'label' => __('Smythe')],
			['value' => 'Sniglet:800', 'label' => __('Sniglet')],
			['value' => 'Special+Elite', 'label' => __('Special Elite')],
			['value' => 'Stardos+Stencil', 'label' => __('Stardos Stencil')],
			['value' => 'Sunshiney', 'label' => __('Sunshiney')],
			['value' => 'Syncopate', 'label' => __('Syncopate')],
			['value' => 'Tangerine', 'label' => __('Tangerine')],
			['value' => 'Tenor+Sans', 'label' => __(' Tenor Sans ')],
			['value' => 'Titillium+Web:700', 'label' => __('Titillium Web Bold')],
			['value' => 'Tinos', 'label' => __('Tinos')],
			['value' => 'Ubuntu', 'label' => __('Ubuntu')],
			['value' => 'Ultra', 'label' => __('Ultra')],
			['value' => 'Unkempt', 'label' => __('Unkempt')],
			['value' => 'UnifrakturCook:bold', 'label' => __('UnifrakturCook')],
			['value' => 'Varela', 'label' => __('Varela')],
			['value' => 'Varela Round', 'label' => __('Varela Round')],
			['value' => 'Vibur', 'label' => __('Vibur')],
			['value' => 'Vollkorn', 'label' => __('Vollkorn')],
			['value' => 'VT323', 'label' => __('VT323')],
			['value' => 'Wallpoet', 'label' => __('Wallpoet')],
			['value' => 'Wire+One', 'label' => __('Wire One')],
			['value' => 'Yeseva+One', 'label' => __('Yeseva One')],
			['value' => 'Zeyada', 'label' => __('Zeyada')],
			/* ['value' => 'other', 'label' => __('Other')], */
		];
	}
}