<?php
/** THIS IS FOR SEARCH RESULT PAGE
 *
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Market\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<div class="toolbar-top">
    <?php echo $block->getToolbarHtml() ?>
	</div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
		$showReview = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
		$showReview = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-product products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
		
		<?php if($viewMode == 'grid'){ ?>
		
        <ol class="art-product-list products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
					<div class="product-item-info" data-container="product-grid">
						<div class="item-inner">
							<div class="box-image">
								<!--2017/11/13 Tenzin: Display Best Seller Badge -->
								<?php
								$enable_best_seller = $_product->getAttributeText('ars_best_seller') === "Best Seller" ? TRUE:FALSE;
								if($enable_best_seller) { ?>
									<div class="art-best-seller-icon-row">
										<span class="art-best-seller-icon-container">
											<span class="art-best-seller-icon-label">
												<?php /* @escapeNotVerified */ echo __('Best ') ?>
												<span><?php /* @escapeNotVerified */ echo __('Seller') ?></span>
											</span>
										</span>
									</div>
								<?php } ?>
								<?php $productImage = $block->getImage($_product, $image);?>
								
								<!--LABEL PRODUCT-->

									<?php
										$specialprice = $_product->getSpecialPrice();
										$specialPriceFromDate = $_product->getSpecialFromDate();
										$specialPriceToDate = $_product->getSpecialToDate();
										
										$today = time();

										if ($specialprice && $_config->getAdvanced('show_salelabel')) {
											if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
												<div class="label-product label-sale">
													<span class="sale-product-icon">
														<?php echo __('Sale'); ?>
													</span>
												</div>
											<?php }
										}
									?>
									
									<?php
									$now = date("Y-m-d");
									$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
									$newsTo = substr($_product->getNewsToDate(), 0, 10);
									
									
									if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
												<div class="label-product label-new">
													<span class="new-product-icon"><?php echo __('New'); ?></span>
												</div>
										<?php }
									} ?>
									
									
								<!--END LABEL PRODUCT-->

								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php echo $productImage->toHtml(); ?>
								</a>
							</div>
							
							<div class="product details product-item-details box-info">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<h2 class="product name product-item-name product-name">
									<a class="clamped ellipsis2Line product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h2>
								<!-- 2017/11/13 Tenzin: Add icons per product -->
								<?php
								//https://magento.stackexchange.com/questions/132098/magento-2-how-to-display-custom-attribute-in-catalog
								//Attributes must be configured to Yes for "Use in Product Listing"
								$custom_packaging = $_product->getAttributeText('ars_custom_packaging_type');
								$enable_ready_to_ship = $_product->getAttributeText('ars_ready_to_ship') === "In Stock" ? TRUE:FALSE;
								$enable_ready_to_assemble = $_product->getAttributeText('ars_ready_to_assemble') === "Yes" ? TRUE:FALSE;
								$enable_product_question = $_product->getAttributeText('ars_product_question') === "Yes" ? TRUE:FALSE;
								//Next two attributes returns string of all values joined by commas
								$enable_packaging_recyclable = $_product->getResource()->getAttribute('ars_packaging_recyclable')->getFrontend()->getValue($_product) === "Yes" ? TRUE:FALSE;
								$enable_shipping_icon = $_product->getResource()->getAttribute('ars_ltl_shipment')->getFrontend()->getValue($_product)=== "Yes" ? TRUE:FALSE;
								//Combining Packaging Recyclable and Shipment Type values to only loop through once
								//$enable_packaging_shipping = $enable_packaging_recyclable . ',' . $enable_shipping_icon;
								//Checking if any of the icons are enabled
								if( $enable_ready_to_assemble || $enable_product_question || $enable_ready_to_ship || $enable_packaging_recyclable || $enable_shipping_icon ) { ?>
								<div class="art-description-icons">
								<?php if( $enable_ready_to_ship ) { ?>
										<span class="art-ready-to-ship" >In Stock!</span>
								<?php } ?>
								<?php if( $enable_packaging_recyclable ) { ?>
										<img class="art-packaging-recyclable" title="This item can be used more than once!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Label_Sticker_Icon_1_Green.png" />
								<?php } ?>
								<?php if( $enable_shipping_icon ) { ?>
										<img class="art-shipping" title="It will take, at most, 24 Hours to ship this product." src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/shipping-24.png" />
								<?php } ?>
								<?php if( $enable_ready_to_assemble ) { ?>
										<img class="art-ready-to-assemble" title="This item will come disassembled and needs to be put together by you!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Display_Case_Icon_Red.png" />
								<?php } ?>
								<?php if( $enable_product_question ) { ?>
										<img class="art-product-question" title="Have any question about this item? Click here to request help!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/IT_Consulting_Icon_Yellow.png" />
								<?php } ?>
								</div>
								<?php } ?>
								<?php if ($showReview):?>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
								<?php endif; ?>
								
								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								<?php echo $block->getProductDetailsHtml($_product); ?>
								
								<div class="product-item-inner">
									<?php if ($showDescription):?>
										<div class="art-catalog-listing-description ellipsis1Line product description product-item-description">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										</div>
									<?php endif; ?>
								</div>
								
								<div class="bottom-action">
                                <!-- 2018-02-23 TK & SM: Adding QTY to each product grid-->
                                    <div class="info-box-detail">
                                    <div class="box-tocart">
                                    <div class="fieldset">
                                    <div class="field qty">
                                        <div class="control control-qty-cart">
                                            <input type="number"
                                                   name="qty"
                                                   id="qty-<?php echo $_product->getData('sku'); ?>"
                                                   maxlength="12"
                                                   value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>"
                                                   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="qty-default input-text qty"
                                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                                   />
                                                   
                                            <div class="control-qty">
                                                <span id="plus-<?php echo $_product->getData('sku'); ?>" class="quantity-controls quantity-plus"></span>
                                                <span id="minus-<?php echo $_product->getData('sku'); ?>" class="quantity-controls quantity-minus"></span>

                                                <script type="text/javascript">
                                                    require([
                                                        'jquery'
                                                    ], function ($) {
                                                        var product_id = '#qty-<?php echo $_product->getData('sku'); ?>';
                                                        var product_plus = '#plus-<?php echo $_product->getData('sku'); ?>';
                                                        var product_minus = '#minus-<?php echo $_product->getData('sku'); ?>';
                                                        var form_qty = '#input-qty-<?php echo $_product->getData('sku'); ?>';
                                                        
                                                        
                                                        $(product_plus).click(function () {
                                                            var value = Number($(product_id).val()) + 1;
                                                            $(product_id).val(value);
                                                            $(form_qty).val(value);
                                                        });
                                                        
                                                        $(product_minus).click(function () {
                                                            var value = Number($(product_id).val()) - 1;
                                                            if (value > 0) {
                                                                $(product_id).val(value);
                                                                $(form_qty).val(value);
                                                            }
                                                            
                                                        });
                                                    });
                                                </script>
                                            </div>
                                        </div>
                                    </div>
									</div><!--fieldset-->
                                    </div><!--box-tocart-->
                                    </div> <!--info-box-detail-->
                                    <?php if($_config->getAdvanced('show_addtocart_button')){?>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<input id="input-qty-<?php echo $_product->getData('sku'); ?>" type="hidden" name="qty" />
                                                <?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart primary btn-action btn-cart">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									<?php } ?>
									
									<?php if($_config->getAdvanced('show_wishlist_button')){?>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist"  role="button">
												<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
											</a>
										<?php endif; ?>
									<?php } ?>
									
									<?php if($_config->getAdvanced('show_compare_button')){?>
										<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
										<a href="#"  class="action tocompare btn-action link-compare"  title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
											<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
										</a>
									<?php } ?>
									<?php if ( $custom_packaging !== "Not Applicable" && $custom_packaging ) {
										//attributes to send to form
										$name = $_helper->productAttribute($_product, $_product->getName(), 'name');
										$sku = $_product->getData('sku');
										$dimensions = $_product->getResource()->getAttribute('ars_dims')->getFrontend()->getValue($_product);
										$color = $_product->getResource()->getAttribute('ars_color')->getFrontend()->getValue($_product);
										
										//Custom Page
										if ( $custom_packaging === "Custom Shopping Bags" ) {
											$href = "/custom-shopping-bags/";
										}elseif ( $custom_packaging === "Custom Tissue" ) {
											$href = "/custom-tissue-paper-and-gift-wraps/";
										}elseif ( $custom_packaging === "Custom Tags & Labels" ) {
											$href = "/custom-labels-and-stickers/";
										}elseif ( $custom_packaging === "Custom Boxes" ) {
											$href = "/custom-boxes/";
										}

										$href .= "?product-name=" . urlencode($name) . "&custom-packaging-sku=" . urlencode($sku) . "&dimensions=" .  urlencode($dimensions) . "&color=" . urlencode($color);
										
										//Change type of double quote that is acceptable in input value at form page
										$href = str_replace ('%26quot%3B','%22', $href);
										?>
										<a href="<?php /* @escapeNotVerified */ echo htmlentities($href);?>" target="_blank">
											<button title="Customize this item by adding your logo." class="art btn-action btn-cart art-custom-button primary btn-action ellipsis1Line clamped"><span>Add Logo</span></button>
										</a>
									<?php } ?>
								</div>
								<span class="art-product-listing-sku">SKU: <?php /* @escapeNotVerified */ echo $_product->getData('sku') ?></span>
							</div>
						</div>
					</div>
                </li>
            <?php endforeach; ?>
        </ol>
		
		<?php } else {?>
			<ol class="products list items product-items">
				<?php foreach ($_productCollection as $_product): ?>
					<li class="item respl-item-list product product-item">
						<div class="product-item-info" data-container="product-grid">
							<div class="item-inner">
								<div class="box-image-list">
									<!--2017/11/13 Tenzin: Display Best Seller Badge -->
									<?php
									$enable_best_seller = $_product->getAttributeText('ars_best_seller') === "Best Seller" ? TRUE:FALSE;
									if($enable_best_seller) { ?>
										<div class="art-best-seller-icon-row">
											<span class="art-best-seller-icon-container">
												<span class="art-best-seller-icon-label">
													<?php /* @escapeNotVerified */ echo __('Best ') ?>
													<span><?php /* @escapeNotVerified */ echo __('Seller') ?></span>
												</span>
											</span>
										</div>
									<?php } ?>
									<?php $productImage = $block->getImage($_product, $image); ?>
									
									<!--LABEL PRODUCT-->

										<?php
											$specialprice = $_product->getSpecialPrice();
											$specialPriceFromDate = $_product->getSpecialFromDate();
											$specialPriceToDate = $_product->getSpecialToDate();
											
											$today = time();

											if ($specialprice && $_config->getAdvanced('show_salelabel')) {
												if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
													<div class="label-product label-sale">
														<span class="sale-product-icon">
															<?php echo __('Sale'); ?>
														</span>
													</div>
												<?php }
											}
										?>
										
										<?php
										$now = date("Y-m-d");
										$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
										$newsTo = substr($_product->getNewsToDate(), 0, 10);
										
										
										if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
											if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
													<div class="label-product label-new">
														<span class="new-product-icon"><?php echo __('New'); ?></span>
													</div>
											<?php }
										} ?>
										
										
									<!--END LABEL PRODUCT-->

									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<?php echo $productImage->toHtml(); ?>
									</a>

								</div>
								
								<div class="product details product-item-details box-info-list">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<h2 class="product name product-item-name product-name">
										<a class="clamped ellipsis2Line product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h2>
									<!-- 2017/11/13 Tenzin: Add icons per product -->
									<?php
									//https://magento.stackexchange.com/questions/132098/magento-2-how-to-display-custom-attribute-in-catalog
									//Attributes must be configured to Yes for "Use in Product Listing"
									$custom_packaging = $_product->getAttributeText('ars_custom_packaging_type');
									$enable_ready_to_ship = $_product->getAttributeText('ars_ready_to_ship') === "In Stock" ? TRUE:FALSE;
									$enable_ready_to_assemble = $_product->getAttributeText('ars_ready_to_assemble') === "Yes" ? TRUE:FALSE;
									$enable_product_question = $_product->getAttributeText('ars_product_question') === "Yes" ? TRUE:FALSE;
									//Next two attributes returns string of all values joined by commas
									$enable_packaging_recyclable = $_product->getResource()->getAttribute('ars_packaging_recyclable')->getFrontend()->getValue($_product) === "Yes" ? TRUE:FALSE;
									$enable_shipping_icon = $_product->getResource()->getAttribute('ars_ltl_shipment')->getFrontend()->getValue($_product)=== "Yes" ? TRUE:FALSE;
									//Combining Packaging Recyclable and Shipment Type values to only loop through once
									//$enable_packaging_shipping = $enable_packaging_recyclable . ',' . $enable_shipping_icon;
									//Checking if any of the icons are enabled
									if( $enable_ready_to_assemble || $enable_product_question || $enable_ready_to_ship || $enable_packaging_recyclable || $enable_shipping_icon ) { ?>
									<div class="art-description-icons">
									<?php if( $enable_ready_to_ship ) { ?>
											<span class="art-ready-to-ship" >In Stock!</span>
									<?php } ?>
									<?php if( $enable_packaging_recyclable ) { ?>
											<img class="art-packaging-recyclable" title="This item can be used more than once!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Label_Sticker_Icon_1_Green.png" />
									<?php } ?>
									<?php if( $enable_shipping_icon ) { ?>
											<img class="art-shipping" title="It will take, at most, 24 Hours to ship this product." src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/shipping-24.png" />
									<?php } ?>
									<?php if( $enable_ready_to_assemble ) { ?>
											<img class="art-ready-to-assemble" title="This item will come disassembled and needs to be put together by you!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Display_Case_Icon_Red.png" />
									<?php } ?>
									<?php if( $enable_product_question ) { ?>
											<img class="art-product-question" title="Have any question about this item? Click here to request help!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/IT_Consulting_Icon_Yellow.png" />
									<?php } ?>
									</div>
									<?php } ?>
									<span>SKU # <?php /* @escapeNotVerified */ echo $_product->getData('sku') ?></span>
								
									<?php if ($showReview):?>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
									<?php endif; ?>
									
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<?php echo $block->getProductDetailsHtml($_product); ?>
									
									<div class="product-item-inner">
										<?php if ($showDescription):?>
											<div class="art-catalog-listing-description ellipsis1Line product description product-item-description">
												<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
												   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
											</div>
										<?php endif; ?>
									</div>
									
									<div class="bottom-action">
										<?php if($_config->getAdvanced('show_addtocart_button')){?>
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart btn-action btn-cart">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										<?php } ?>
										
										<div class="add-to-links" data-role="add-to-links" class="actions-secondary">
											<?php if($_config->getAdvanced('show_wishlist_button')){?>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
													<a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist"  role="button">
														<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
													</a>
												<?php endif; ?>
											<?php } ?>
											
											<?php if($_config->getAdvanced('show_compare_button')){?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
												<a href="#"  class="action tocompare btn-action link-compare"  title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
													<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
												</a>
											<?php } ?>
											<?php if ( $custom_packaging !== "Not Applicable" && $custom_packaging ) {
												//attributes to send to form
												$name = $_helper->productAttribute($_product, $_product->getName(), 'name');
												$sku = $_product->getData('sku');
												$dimensions = $_product->getResource()->getAttribute('ars_dims')->getFrontend()->getValue($_product);
												$color = $_product->getResource()->getAttribute('ars_color')->getFrontend()->getValue($_product);
												
												//Custom Page
												if ( $custom_packaging === "Custom Shopping Bags" ) {
													$href = "/custom-shopping-bags/";
												}elseif ( $custom_packaging === "Custom Tissue" ) {
													$href = "/custom-tissue-paper-and-gift-wraps/";
												}elseif ( $custom_packaging === "Custom Tags & Labels" ) {
													$href = "/custom-labels-and-stickers/";
												}elseif ( $custom_packaging === "Custom Boxes" ) {
													$href = "/custom-boxes/";
												}

												$href .= "?product-name=" . urlencode($name) . "&custom-packaging-sku=" . urlencode($sku) . "&dimensions=" .  urlencode($dimensions) . "&color=" . urlencode($color);
												
												$href = str_replace ('%26quot%3B','%22', $href);
												?>
												<a href="<?php /* @escapeNotVerified */ echo htmlentities($href);?>" target="_blank">
													<button title="Customize this item by adding your logo." class="art btn-action btn-cart art-custom-button primary btn-action ellipsis1Line clamped"><span>Add Your Logo</span></button>
												</a>
											<?php } ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			</ol>
		<?php } ?>
    </div>
	<div class="toolbar-bottom">
    <?php echo $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
