<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $block->getFieldId() ?>"<?php if ($block->isRequired()) echo ' class="required"' ?>><?php if ($block->isRequired()) echo '<em>*</em>' ?><?php echo $block->getLabel() ?></label>
    <div class="input-box">
        <?php $options = $block->getGenderOptions() ?>
        <input type="radio" name="<?php echo $block->getFieldName() ?>" title="<?php echo $block->getLabel() ?>" id="<?php echo $block->getFieldId() ?>-female" value="<?php echo $options[1]['value'] ?>" style="vertical-align:middle;" />
        <label for="<?php echo $block->getFieldId() ?>-female"><?php echo __('Female') ?></label>
        <input type="radio" name="<?php echo $block->getFieldName() ?>" title="<?php echo $block->getLabel() ?>" id="<?php echo $block->getFieldId() ?>-male" value="<?php echo $options[0]['value'] ?>" style="vertical-align:middle;" />
        <label for="<?php echo $block->getFieldId() ?>-male"><?php echo __('Male') ?></label>
    </div>
</div>