<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="field">
    <label for="<?php echo $block->getFieldId() ?>" class="required"><em>*</em><?php echo $block->getLabel() ?></label>
    <div class="input-box">
        <input type="text" name="street" value="" placeholder="<?php echo $block->getLabel() ?>" title="<?php echo $block->getLabel() ?>" id="<?php echo $block->getFieldId() ?>" class="street-field input-text required-entry <?php echo $block->getAttributeValidationClass('street') ?>" />
    </div>
</div>