#!/bin/sh
php /opt/bitnami/apps/magento/htdocs/bin/magento indexer:reindex
sudo chmod -R 777 /opt/bitnami/apps/magento/htdocs/var /opt/bitnami/apps/magento/htdocs/pub /opt/bitnami/apps/magento/htdocs/app/etc
