#!/bin/sh
sudo rm -rf /opt/bitnami/apps/magento/htdocs/var/view_preprocessed/* /opt/bitnami/apps/magento/htdocs/var/cache/* /opt/bitnami/apps/magento/htdocs/var/page_cache/* /opt/bitnami/apps/magento/htdocs/var/generation/* /opt/bitnami/apps/magento/htdocs/pub/static/*
php /opt/bitnami/apps/magento/htdocs/bin/magento cache:flush
php /opt/bitnami/apps/magento/htdocs/bin/magento setup:upgrade
php /opt/bitnami/apps/magento/htdocs/bin/magento setup:di:compile
php /opt/bitnami/apps/magento/htdocs/bin/magento setup:static-content:deploy
php /opt/bitnami/apps/magento/htdocs/bin/magento indexer:reindex
sudo chmod -R 777 /opt/bitnami/apps/magento/htdocs/pub /opt/bitnami/apps/magento/htdocs/var /opt/bitnami/apps/magento/htdocs/app /opt/bitnami/apps/magento/htdocs/scripts
