#!/bin/sh

#https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
RED='\033[0;31m'
NC='\033[0m' #No color

WEBSITE="https://staging.americanretailsupply.com/"
ROBOT_NO_FOLLOW="NOINDEX,NOFOLLOW"
ROBOT_FILE="User-agent: *
Disallow: /index.php/
Disallow: /*?
Disallow: /checkout/
Disallow: /app/
Disallow: /lib/
Disallow: /*.php$
Disallow: /pkginfo/
Disallow: /report/
Disallow: /var/
Disallow: /catalog/
Disallow: /customer/
Disallow: /sendfriend/
Disallow: /review/"
AUTH_TEST_MODE="1"
CHECK_MONEY_ACTIVE="1"
ANALYTICS_ACTIVE="0"
ADWORD_ACTIVE="0"
CC_ORDER_EMAIL=""

mysql --host=ars-mysql.crymzjqricqv.us-west-2.rds.amazonaws.com -u ars_dbroot -D ars_staging_magento1 -e "update core_config_data set value = '$WEBSITE' where config_id = 1;update core_config_data set value = '$WEBSITE' where config_id = 2; select path, value from core_config_data LIMIT 4; update core_config_data set value = '$ROBOT_NO_FOLLOW' where config_id = 999; update core_config_data set value = '$ROBOT_FILE' where config_id = 1000; update core_config_data set value = '$AUTH_TEST_MODE' where config_id = 1118; update core_config_data set value ='$CHECK_MONEY_ACTIVE' where config_id = 1029; update core_config_data set value ='$ANALYTICS_ACTIVE' where config_id = 1045; update core_config_data set value ='$ADWORD_ACTIVE' where config_id = 1123; update core_config_data set value ='$CC_ORDER_EMAIL' where config_id = 1065;" -p 
cd /opt/bitnami/apps/magento/htdocs/scripts
cp env.staging.php ../app/etc/env.php
./regen
#PageTraffic Account
/opt/bitnami/php/bin/php /opt/bitnami/apps/magento/htdocs/bin/magento admin:user:create --admin-firstname=Page --admin-lastname=Traffic --admin-email=jatin@pagetraffic.org --admin-user=pagetraffic --admin-password=pagetraffic988
#Mark Turner Account
/opt/bitnami/php/bin/php /opt/bitnami/apps/magento/htdocs/bin/magento admin:user:create --admin-firstname=Mark --admin-lastname=Turner --admin-email=mark@americanretailsupply.com --admin-user=mark --admin-password=mark1313
#Surender Account
/opt/bitnami/php/bin/php /opt/bitnami/apps/magento/htdocs/bin/magento admin:user:create --admin-firstname=Surender --admin-lastname=Mohan --admin-email=surender@americanretailsupply.com --admin-user=mark --admin-password=American1
#Nishita Account
/opt/bitnami/php/bin/php /opt/bitnami/apps/magento/htdocs/bin/magento admin:user:create --admin-firstname=Nishita --admin-lastname=Mohan --admin-email=nishita@americanretailsupply.com --admin-user=mark --admin-password=American1
#update htaccess file
crontab crontab_staging
cp staging.htaccess.conf /opt/bitnami/apps/magento/conf/htaccess.conf
sudo /opt/bitnami/ctlscript.sh restart apache