#!/bin/sh

#https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
RED='\033[0;31m'
NC='\033[0m' #No color

WEBSITE="https://dev.americanretailsupply.com/"
ROBOT_NO_FOLLOW="NOINDEX,NOFOLLOW"
ROBOT_FILE="User-agent: *
Disallow: /index.php/
Disallow: /*?
Disallow: /checkout/
Disallow: /app/
Disallow: /lib/
Disallow: /*.php$
Disallow: /pkginfo/
Disallow: /report/
Disallow: /var/
Disallow: /catalog/
Disallow: /customer/
Disallow: /sendfriend/
Disallow: /review/"
AUTH_TEST_MODE="1"
CHECK_MONEY_ACTIVE="1"
ANALYTICS_ACTIVE="0"
ADWORD_ACTIVE="0"
CC_ORDER_EMAIL="webadmin@americanretailsupply.com"

mysql -u ars_dbroot -D ars_prod_magento1 -e "update core_config_data set value = '$WEBSITE' where config_id = 1;update core_config_data set value = '$WEBSITE' where config_id = 2; select path, value from core_config_data LIMIT 4; update core_config_data set value = '$ROBOT_NO_FOLLOW' where config_id = 999; update core_config_data set value = '$ROBOT_FILE' where config_id = 1000; update core_config_data set value = '$AUTH_TEST_MODE' where config_id = 1118; update core_config_data set value ='$CHECK_MONEY_ACTIVE' where config_id = 1029; update core_config_data set value ='$ANALYTICS_ACTIVE' where config_id = 1045; update core_config_data set value ='$ADWORD_ACTIVE' where config_id = 1123; update core_config_data set value ='$CC_ORDER_EMAIL' where config_id = 1065;" -p 
cd /opt/bitnami/apps/magento/htdocs/scripts
./regen
echo "${RED}Comment out Cron jobs${NC}"
