<div class="header-container header-style-5">
	<div class="header-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4 language-currency">
					<?php echo $block->getChildHtml('language-header'); ?>
					<?php echo $block->getChildHtml('currency-header'); ?>
				</div>
				
				<div class="col-lg-8 col-md-8  toplinks-wrapper">
					<?php echo $block->getChildHtml('toplinks-header'); ?>
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-middle">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-5 col-sm-4 search-box">
					<?php echo $block->getChildHtml('search-header-pro'); ?>
				</div>
				
				<div class="col-lg-2 col-md-2 col-sm-4 logo-container">
					<?php echo $block->getChildHtml('logo-header'); ?>
				</div>
				
				<div class="col-lg-5 col-md-5 col-sm-4 phone-cart">
					<?php echo $block->getChildHtml('cart-header'); ?>
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('phone-header-v5')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
	
	<div class="slidershow-header">
		<?php echo $block->getChildHtml('slideshow-header'); ?>
	</div>
	
	<div class="header-bottom">
		<div class="container">
			<div class="menu-horizontal-hd5">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml(); ?>
			</div>
			
			<div class="navigation-mobile-container">
				<?php echo $block->getChildHtml('navigation.mobile'); ?>
			</div>
		</div>
		
	</div>
</div>
