<?php 
	$_config = $this->helper('Sm\Market\Helper\Data');
	$locale = $_config->getLocale();

	$full_path =  dirname(__FILE__);
	$arr_full_path = explode('app',$full_path);
	$root_path = '/';
	if(isset($arr_full_path[0])) $root_path = $arr_full_path[0];
	$root_path .= 'apps/magento/htdocs/'; // Surender - 04/01/2017 - Fix for windows
	
	//Absolute Path
	$megamenu_vertical_path = $root_path.'pub/static/frontend/Sm/market/'.$locale.'/Magento_Theme/megamenu-vertical.html';
	
	if(!file_exists($megamenu_vertical_path)){
		$megamenu_vertical = $block->getChildHtml('navigation-header-megamenu');
		file_put_contents($megamenu_vertical_path,$megamenu_vertical);
	}
	
	//path from url. changes each time static-content is deployed
	$url_static = $_config->getUrlStatic();
	$megamenu_vertical_file = $url_static . 'frontend/Sm/market/'.$locale.'/Magento_Theme/megamenu-vertical.html';
	
	$welcomeMessage = $block->getWelcome(); ?>

<div class="header-container header-style-2">
	<div class="header-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-5 col-sm-3 customer-action-header">
					<div class="customer-action-hd">
						<span class="welcome-text">

							<span class="greet welcome" data-bind="scope: 'customer'">
								<!-- ko if: customer().fullname  -->
								<span data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)">
								</span>
								<!-- /ko -->
								<!-- ko ifnot: customer().fullname  -->
								<span data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
								<!-- /ko -->
							</span>
							<script type="text/x-magento-init">
							{
								"*": {
									"Magento_Ui/js/core/app": {
										"components": {
											"customer": {
												"component": "Magento_Customer/js/view/customer"
											}
										}
									}
								}
							}
							</script>

						</span>
						
						<?php
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$customerSession = $objectManager->get('Magento\Customer\Model\Session');
						?>
						
						<?php if($customerSession->isLoggedIn()){?>
							<a href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo __('Logout')?>"><?php echo __('Logout')?></a>
						<?php } else {?>
							<a href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo __('Sign In')?>"><?php echo __('Sign in')?></a>
						<?php } ?>
					</div>
				</div>
				
				<div class="col-lg-7 col-md-7 col-sm-9 header-top-links">
					<?php echo $block->getChildHtml('currency-header'); ?>
					<?php echo $block->getChildHtml('language-header'); ?>
					<?php echo $block->getChildHtml('toplinks-header'); ?>
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-middle">
		<div class="container">
			<div class="row">
				<div class="col-lg-2 col-md-2 logo-header">
					<?php echo $block->getChildHtml('logo-header'); ?>
				</div>
				
				<div class="col-lg-10 col-md-10 header-middle-right">
					<div class="middle-right-content">
						<div class="main-megamenu">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();?>
						</div>
						
						<div class="minicart-header">
							<div class="minicart-content">
								<?php echo $block->getChildHtml('cart-header'); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-bottom">
		<div class="container">
			<div class="row">
				<div class="navigation-mobile-container">
					<?php echo $block->getChildHtml('navigation.mobile'); ?>
				</div>
				
				<div class="col-lg-3 col-md-3 sidebar-megamenu">
					<div class="megamenu-content-sidebar">
						<div class="btn-megamenu">
							<a href="javascript:void(0)" title="<?php echo __('All Categories')?>"><?php echo __('All Categories')?></a>
						</div>
						
						<div class="menu-ver-content">
							<?php if($_config->getGeneral('menu_style') == 'megamenu'){ ?>
									<div art-include-html="<?php /* @escapeNotVerified */ echo $megamenu_vertical_file ?>"></div>
							<?php } else {
									echo $block->getChildHtml('navigation-header');
								}
							?>
						</div>
					</div>
				</div>
				
				<div class="col-lg-9 col-md-9 searchbox-header">
					<?php echo $block->getChildHtml('search-header-pro'); ?>
				</div>
			</div>
		</div>
	</div>
</div>
