<?php 
	$_config = $this->helper('Sm\Market\Helper\Data');
	$locale = $_config->getLocale();
	$headerStyle = $_config->getThemeLayout('header_style');

	$full_path =  dirname(__FILE__);
	$arr_full_path = explode('app',$full_path);
	$root_path = '/';
	if(isset($arr_full_path[0])) $root_path = $arr_full_path[0];
	$root_path .= 'apps/magento/htdocs/'; // Surender - 04/01/2017 - Fix for windows
	
	//Absolute Path
	$megamenu_vertical_path = $root_path.'pub/static/frontend/Sm/market/'.$locale.'/Magento_Theme/megamenu-vertical.html';
	
	if(!file_exists($megamenu_vertical_path)){
		$megamenu_vertical = $block->getChildHtml('navigation-header-megamenu');
		file_put_contents($megamenu_vertical_path,$megamenu_vertical);
	}
	
	//path from url. changes each time static-content is deployed
	$url_static = $_config->getUrlStatic();
	$megamenu_vertical_file = $url_static . 'frontend/Sm/market/'.$locale.'/Magento_Theme/megamenu-vertical.html';
	
	$welcomeMessage = $block->getWelcome(); ?>

<div class="header-container header-style-2">
	<div class="header-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-5 col-sm-3 customer-action-header">
					<div class="customer-action-hd">
						<span class="welcome-text">

							<span class="greet welcome" data-bind="scope: 'customer'">
								<!-- ko if: customer().fullname  -->
								<span data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)">
								</span>
								<!-- /ko -->
								<!-- ko ifnot: customer().fullname  -->
								<span data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
								<!-- /ko -->
							</span>
							<script type="text/x-magento-init">
							{
								"*": {
									"Magento_Ui/js/core/app": {
										"components": {
											"customer": {
												"component": "Magento_Customer/js/view/customer"
											}
										}
									}
								}
							}
							</script>

						</span>
						
						<?php
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$customerSession = $objectManager->get('Magento\Customer\Model\Session');
						?>
						
						<?php if($customerSession->isLoggedIn()){?>
							<a href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo __('Logout')?>"><?php echo __('Logout')?></a>
						<?php } else {?>
							<a href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo __('Sign In')?>"><?php echo __('Sign in')?></a>
						<?php } ?>
					</div>
				</div>
				
				<div class="col-lg-7 col-md-7 col-sm-9 header-top-links">
					<?php echo $block->getChildHtml('currency-header'); ?>
					<?php echo $block->getChildHtml('language-header'); ?>
					<?php echo $block->getChildHtml('toplinks-header'); ?>
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-middle">
		<div class="container">
			<div class="row">
				<div class="col-lg-2 col-md-2 logo-header">
					<?php echo $block->getChildHtml('logo-header'); ?>
				</div>
				
				<div class="col-lg-10 col-md-10 header-middle-right">
					<div class="middle-right-content">
						<div class="main-megamenu">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();?>
						</div>
						
						<div class="minicart-header">
							<div class="minicart-content">
								<?php echo $block->getChildHtml('cart-header'); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-bottom">
		<div class="container">
			<div class="row">
				<div class="navigation-mobile-container">
					<?php echo $block->getChildHtml('navigation.mobile'); ?>
				</div>
				
				<div class="col-lg-3 col-md-3 sidebar-megamenu">
					<div class="megamenu-content-sidebar">
						<div class="btn-megamenu">
							<a href="javascript:void(0)" title="<?php echo __('All Categories')?>"><?php echo __('All Categories')?></a>
						</div>
						
						<div class="menu-ver-content">
							<?php if($_config->getGeneral('menu_style') == 'megamenu'){ ?>
									<div art-include-html="<?php /* @escapeNotVerified */ echo $megamenu_vertical_file ?>"></div>
							<?php } else {
									echo $block->getChildHtml('navigation-header');
								}
							?>
						</div>
					</div>
				</div>
				
				<div class="col-lg-9 col-md-9 searchbox-header">
					<?php echo $block->getChildHtml('search-header-pro'); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<!--NAV MOBILE / CSS MENU / MEGAMENU-->
<!--Move this code below last art-include-html-->
<!--2017-10-10 Moved from Magento_Theme:nav-mobile.phtml-->
<script type="text/javascript">
	art.includeHTML();
	require([
		'jquery'
	], function ($) {
		<?php if($_config->getGeneral('responsive_menu') == 'sidebar'){ ?>
		$('#sidebar-button').click(function(){
			$('body').toggleClass('navbar-active');
			$(this).toggleClass('active');
		});
		<?php }else{ ?>
		$('#collapse-button').click(function(){
			$('.navigation-mobile').slideToggle(200);
			$(this).toggleClass('active');
		});
		<?php } ?>
		$('.navigation-mobile > ul li').has('ul').append( '<span class="touch-button"><span>open</span></span>' );
		$('.touch-button').click(function(){
			$(this).prev().slideToggle(200);
			$(this).toggleClass('active');
			$(this).parent().toggleClass('parent-active');
		});
	});
</script>
<!--2017-10-10 Moved from Sm_Megamenu:megamenu.phtml-->
<script type="text/javascript">
	require(["jquery", "mage/template"], function($) {
		var menu_width = $('.sm_megamenu_wrapper_horizontal_menu').width();
		$('.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li > div').each(function () {
			$this = $(this);
			var lv2w = $this.width();
			var lv2ps = $this.position();
			var lv2psl = $this.position().left;
			var sw = lv2w + lv2psl;
			if (sw > menu_width) {
				$this.css({'right': '0'});
			}
		});
		var _item_active = $('div.sm_megamenu_actived');
		if(_item_active.length){
			_item_active.each(function(){
				var _self = $(this), _parent_active =  _self.parents('.sm_megamenu_title') ,_level1 = _self.parents('.sm_megamenu_lv1');
				if(_parent_active.length  ){
					_parent_active.each(function(){
						if(!$(this).hasClass('sm_megamenu_actived'))
							$(this).addClass('sm_megamenu_actived');
					});
				}

				if(_level1.length && !_level1.hasClass('sm_megamenu_actived')){
					_level1.addClass('sm_megamenu_actived');
				}
			});
		}
	});
</script>
<!--2017-10-10 Moved from Sm_Megamenu:megamenu.phtml-->
<script type="text/javascript">
	require([
		'jquery'
	], function ($) {
		var limit;
		limit = 13;
		<?php if($headerStyle == 'header-2'){?>
			limit = 9;
		<?php } ?>
		
		<?php if($headerStyle == 'header-7' || $headerStyle == 'header-8'){?>
			limit = 11;
		<?php } ?>
		
		var i;
		i=0;
		var items;
		items = $('.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li').length;
		
		if(items > limit){
			$('.sm_megamenu_wrapper_vertical_menu .sambar-inner').append('<div class="more-w"><span class="more-view">More Categories</span></div>');
			
			$('.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li').each(function(){
				i++;
				if( i > limit ){
					$(this).css('display', 'none');
				}
			});
			
			$('.sm_megamenu_wrapper_vertical_menu .sambar-inner .more-w > .more-view').click(function(){
				if($(this).hasClass('open')){
					i=0;
					$('.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li').each(function(){
						i++;
						if(i>limit){
							$(this).slideUp(200);
						}
					});
					$(this).removeClass('open');
					$('.more-w').removeClass('active-i');
					$(this).text('More Categories');
				}else{
					i=0;
					$('.sm_megamenu_wrapper_vertical_menu ul.sm_megamenu_menu > li').each(function(){
						i++;
						if(i>limit){
							$(this).slideDown(200);
						}
					});
					$(this).addClass('open');
					$('.more-w').addClass('active-i');
					$(this).text('Close Menu');
				}
			});

		}

	});
</script>
