<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

$lists = $block->getLists();
if (sizeof($lists) > 0) echo '<h3>' . __('Mailing List(s)') . '</h3>';

$first = true;
$popupId = $block->getPopup()->getId();
foreach ($lists as $key => $item) {
    $id = 'mailchimp_' . $key . $popupId;
    ?>
    <div class="mailchimp_item">
        <input type="radio" name="mailchimp_list" value="<?php echo $key ?>" id="<?php echo $id ?>"<?php if ($first) echo ' checked="checked"' ?>>
        <label for="<?php echo $id ?>"><?php echo $item->getLabel() ?></label>
    </div>
<?php
$first = false;
}