<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

$lists = $block->getLists();
if (sizeof($lists) > 0 ) echo '<h3>' . __('Mailing List(s)') . '</h3>';
?>

<select name="mailchimp_list">
    <?php foreach ($lists as $key => $item): ?>
        <option value="<?php echo $key ?>"><?php echo $item->getLabel() ?></option>
    <?php endforeach; ?>
</select>