<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php

$helper = $this->helper('Plumrocket\SocialLoginFree\Helper\Data');
if ($helper->moduleEnabled()): ?>
    <?php if ($helper->isFakeMail()): ?>
        <script type="text/javascript">
        //<![CDATA[
            require([
                'jquery'
            ], function(pjQuery) {
                // 'use strict';
                pjQuery(document).ready(function(){
                    pjQuery('div.password.current').hide();
                });
            });
        //]]>
        </script>
    <?php endif; ?>
<?php endif; ?>