<?php 
$artProduct = $block->getProduct();
$custom_packaging = $artProduct->getAttributeText('ars_custom_packaging_type');
		\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->debug(json_encode($custom_packaging));
if ( $custom_packaging !== "Not Applicable" && $custom_packaging) {
	$name = $artProduct->getName();
	$sku = $artProduct->getData('sku');
	$dimensions = $artProduct->getResource()->getAttribute('ars_dims')->getFrontend()->getValue($artProduct);
	$color = $artProduct->getResource()->getAttribute('ars_color')->getFrontend()->getValue($artProduct);

	//Custom Shopping Bags Page
	if ( $custom_packaging === "Custom Shopping Bags" ) { ?>
	<a href="/custom-shopping-bags/?product-name=<?php /* @escapeNotVerified */ echo htmlspecialchars($name); ?>&custom-packaging-sku=<?php /* @escapeNotVerified */ echo $sku ?>&dimensions=<?php /* @escapeNotVerified */ echo htmlspecialchars($dimensions) ?>&color=<?php /* @escapeNotVerified */ echo htmlspecialchars($color) ?>" target="_blank">
	<?php }elseif ( $custom_packaging === "Custom Tissue" ) {
	//Custom Tissue Page ?>
		<a href="/custom-tissue-paper-and-gift-wraps/?product-name=<?php /* @escapeNotVerified */ echo htmlspecialchars($name); ?>&custom-packaging-sku=<?php /* @escapeNotVerified */ echo $sku ?>&dimensions=<?php /* @escapeNotVerified */ echo htmlspecialchars($dimensions) ?>&color=<?php /* @escapeNotVerified */ echo htmlspecialchars($color) ?>" target="_blank">
	<?php }elseif ( $custom_packaging === "Custom Tags & Labels" ) {
	//Custom Tissue Page ?>
		<a href="/custom-labels-and-stickers/?product-name=<?php /* @escapeNotVerified */ echo htmlspecialchars($name); ?>&custom-packaging-sku=<?php /* @escapeNotVerified */ echo $sku ?>&dimensions=<?php /* @escapeNotVerified */ echo htmlspecialchars($dimensions) ?>&color=<?php /* @escapeNotVerified */ echo htmlspecialchars($color) ?>" target="_blank">
	<?php } ?>
		<button title="Customize this item by adding your logo." class="art btn-action btn-cart art-custom-button primary btn-action ellipsis1Line clamped mb10"><span>Add Your Logo</span></button>
	</a>
<?php } ?>
