<?php 
$artProduct = $block->getProduct();
$custom_packaging = $artProduct->getAttributeText('ars_custom_packaging_type');
		\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->debug(json_encode($custom_packaging));
if ( $custom_packaging !== "Not Applicable" && $custom_packaging) {
	$name = $artProduct->getName();
	$sku = $artProduct->getData('sku');
	$dimensions = $artProduct->getResource()->getAttribute('ars_dims')->getFrontend()->getValue($artProduct);
	$color = $artProduct->getResource()->getAttribute('ars_color')->getFrontend()->getValue($artProduct);

	//Custom Pages
	if ( $custom_packaging === "Custom Shopping Bags" ) {
		$href = "/custom-shopping-bags/";
	}elseif ( $custom_packaging === "Custom Tissue" ) {
		$href = "/custom-tissue-paper-and-gift-wraps/";
	}elseif ( $custom_packaging === "Custom Tags & Labels" ) {
		$href = "/custom-labels-and-stickers/";
	}elseif ( $custom_packaging === "Custom Boxes" ) {
		$href = "/custom-boxes/";
	}

	$href .= "?product-name=" . urlencode($name) 
			. "&custom-packaging-sku=" . urlencode($sku)
			. "&dimensions=" .  urlencode($dimensions) 
			. "&color=" . urlencode($color);
	
	//Change type of double quote that is acceptable in input value at form page
	$href = str_replace ('%26quot%3B','%22', $href);
	?>
	<a href="<?php /* @escapeNotVerified */ echo htmlentities($href);?>" target="_blank">
		<button title="Customize this item by adding your logo." class="art btn-action btn-cart art-custom-button primary btn-action ellipsis1Line clamped"><span>Add Your Logo</span></button>
	</a>
<?php } ?>
