<?php
/**
 * Copyright © 2017 American Retail Supply. All rights reserved.
 * See COPYING.txt for license details.
 
 Tenzin - Showing specific icons if products are:
			1. Shipped within 24 hours
			2. Best Seller
			3. Need to be assembled by customer
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

$artProduct = $block->getProduct();
$enable_ready_to_assemble = $artProduct->getAttributeText('ars_ready_to_assemble') === "Yes" ? TRUE:FALSE;
$enable_product_question = $artProduct->getAttributeText('ars_product_question') === "Yes" ? TRUE:FALSE;

$enable_best_seller = $artProduct->getAttributeText('ars_best_seller') === "Yes" ? TRUE:FALSE; 
$enable_custom_packaging = $artProduct->getAttributeText('ars_custom_packaging') === "Yes" ? TRUE:FALSE;

//Next two attributes returns string of all values joined by commas
$enable_packaging_recyclable = $artProduct->getResource()->getAttribute('ars_packaging_recyclable')->getFrontend()->getValue($artProduct);
$enable_shipping_icon = $artProduct->getResource()->getAttribute('ars_shipping_type')->getFrontend()->getValue($artProduct);
//Combining Packaging Recyclable and Shipment Type values to only loop through once
$enable_packaging_shipping = $enable_packaging_recyclable . ',' . $enable_shipping_icon;

//Log Mailchimp Data in debug.log
\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->debug(json_encode($enable_packaging_recyclable));
\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->debug(json_encode($enable_shipping_icon));
\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->debug(json_encode($enable_packaging_shipping));
?>
<div class="art-description-icons field-tooltip">
<?php if($enable_ready_to_assemble) { ?>
		<img class="art-ready-to-assemble" title="This item will come disassembled and needs to be put together by you!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Display_Case_Icon_Red.png" />
<?php } ?>
<?php if($enable_product_question) { ?>
	<img class="art-product-question" title="Have any question about this item? Click here to request help!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/IT_Consulting_Icon_Yellow.png" />
<?php } ?>
<?php if(!empty($enable_packaging_shipping)) {
	//convert list of values into array
	//remove any white space in front and end of each value
	$enable_packaging_shipping_array = array_map('trim', explode( ',', $enable_packaging_shipping ));
	foreach($enable_packaging_shipping_array as $type) {
		if($type === "24 Hours") { ?>
			<img class="art-shipping-24hours" title="It will take, at most, 24 Hours to ship this product." src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/shipping-24.png" />
		<?php } elseif($type === "LTL Shipment") { ?>
			<img class="art-ltl-freight" title="This item requires LTL Freight instead of Ground." src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/General_Store_Operations_Icon_Red.png" />
		<?php } elseif($type === "40% Recycled") { ?>
			<img class="art-packaging-recycled" title="This item is made of 40% recycled material!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Shopping_Bag_Icon_Green.png" />
		<?php } elseif($type === "Reusable") { ?>
			<img class="art-packaging-reusable" title="This item can be used more than once!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Label_Sticker_Icon_1_Green.png" />
		<?php } ?>
	<?php } ?>
<?php } ?>
</div>