#!/bin/sh
#Create Custom Page and add button to all pages needed

if [ "$#" -lt 1 ]; then
 echo "Usage: ./blog [prod,staging,dev]" >&2
 exit 1
fi

if [[ $1 == prod ]]; then
	BACKUP_HOST=ars-aurora1-cluster-1.cluster-crymzjqricqv.us-west-2.rds.amazonaws.com
	BACKUP_DBNAME=ars_prod_magento1
elif [[ $1 == staging ]]; then
	BACKUP_HOST=ars-mysql.crymzjqricqv.us-west-2.rds.amazonaws.com
	BACKUP_DBNAME=ars_staging_magento1
elif [[ $1 == dev ]]; then
	BACKUP_HOST=localhost
	BACKUP_DBNAME=ars_prod_magento1
fi
	BACKUP_USER=ars_dbroot
	BACKUP_PASSWORD=`echo QW1lcmljYW4xCg== | base64 --decode`

	BACKUP_FOLDER=/opt/bitnami/apps/magento/htdocs
	BACKUP_FILENAME=aw_blog_post_menu.sql
	BACKUP_FILENAME2=aw_blog_prod.sql

unzip -o /opt/bitnami/apps/ars_files/Aheadworks_Blog.zip -d /opt/bitnami/apps/magento/htdocs/
/opt/bitnami/php/bin/php /opt/bitnami/apps/magento/htdocs/bin/magento module:enable Aheadworks_Blog
/opt/bitnami/apps/magento/htdocs/scripts/regen

#Go to Aheadworks Configuration and import xml file: Squarespace-Wordpress-Export-12-26-2017.xml
#Then, run the two mysql files

#mysql --host=$BACKUP_HOST --user=$BACKUP_USER --password=$BACKUP_PASSWORD $BACKUP_DBNAME < $BACKUP_FOLDER/$BACKUP_FILENAME
#mysql --host=$BACKUP_HOST --user=$BACKUP_USER --password=$BACKUP_PASSWORD $BACKUP_DBNAME < $BACKUP_FOLDER/$BACKUP_FILENAME2
