#!/bin/sh
unzip ~/apps/ars_files/magento2-order-import-export-v11.zip -d /opt/bitnami/apps/magento/htdocs/
rm -f /opt/bitnami/apps/magento/htdocs/magento_2_import_export_sales_orders_documentation.pdf
/opt/bitnami/php/bin/php /opt/bitnami/apps/magento/htdocs/bin/magento module:enable CommerceExtensions_OrderImportExport
