<div class="header-container header-style-10">
	<div class="header-top-services">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-sv-header')->toHtml(); ?>
		</div>
	</div>
	
	<div class="header-wrapper">
		<div class="container">
			<div class="header-top">
				<div class="row">
					<div class="col-lg-3 col-md-3 col-sm-4 language-currency">
						<div class="language-currency-content">
							<?php echo $block->getChildHtml('language-header'); ?>
							<?php echo $block->getChildHtml('currency-header'); ?>
						</div>
					</div>
					
					<div class="col-lg-9 col-md-9 col-sm-8 right-content">
						<div class="action-content">
							<div class="minicart-header">
								<?php echo $block->getChildHtml('cart-header'); ?>
							</div>
							<?php echo $block->getChildHtml('toplinks-header'); ?>
						</div>
					</div>
				</div>
			</div>
			
			<div class="header-middle">
				<div class="row">
					<div class="col-lg-4 col-md-4">
					</div>
					
					<div class="col-lg-4 col-md-4 logo-header">
						<?php echo $block->getChildHtml('logo-header'); ?>
					</div>
					
					<div class="col-lg-4 col-md-4 searchbox-header">
						<?php echo $block->getChildHtml('search-header'); ?>
					</div>
				</div>
			</div>
			
			<div class="header-bottom">
				<div class="row">
					<div class="col-lg-9 col-md-12 main-megamenu">
						<div class="menu-full">
						<?php
							if($_config->getGeneral('menu_style') == 'megamenu'){
								echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
							} else {
								echo $block->getChildHtml('navigation-header');
							}
						?>
						</div>
						
						<div class="navigation-mobile-container">
							<?php echo $block->getChildHtml('navigation.mobile'); ?>
						</div>
					</div>
					
					<div class="col-lg-3 col-md-3 link-right">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link-right-header')->toHtml(); ?>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>
