<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<div class="newspopup_up_bg" id="newspopup_up_bg_<?php echo (int)$block->getPopup()->getId(); ?>" style="background: none; position: static;">
    <?php echo $block->getChildHtml('popup.body'); ?>
</div>
<style type="text/css">
    body {
        width:800px!important;
    }

    ol, ul {
        list-style: outside none none;
        padding: 0;
        margin: 0;
    }
    .newspopup_up_bg {
        padding: 0!important;
        margin: auto!important;
    }
    .newspopup-theme {
        max-width: 860px;
    }

    .newspopup-animated-form {
        margin-top:0px!important;
    }
</style>