<?php
/*------------------------------------------------------------------------
# SM Basic Products - Version 2.1.0
# Copyright (c) 2015 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $block->_getSelectSource();
$helper = $this->_helper();
	
if (!empty($list)) { ?>

    <?php if ($this->_getConfig('pretext') != null) { ?>
		<div class="bs-pretext">
			<?php echo $this->_getConfig('pretext'); ?>
		</div>
	<?php } ?>

	

    <div class="block products-sidebar">
		<?php if ($this->_getConfig('display_title', 1)) { ?>
			<?php if ($this->_getConfig('title')) { ?>
				<div class="block-title filter-title">
					<strong><?php echo $this->_getConfig('title', 'Sm Basic Products'); ?></strong>
				</div>
			<?php } ?>
		<?php } ?>
        <!-- Begin bs-items     -->
        <div class="block-content block-content-products">
            <div class="row">
			<?php foreach ($list as $_product) { ?>
				<!-- Begin bs-item-cf -->
                <div class="col-lg-12 col-sm-6 mb10 item bs-item cf">
                    <!-- Begin bs-item-inner -->
                    <div class="item-inner">
                        <?php if ($_product->_image) { ?>
                            <div class="box-image">
                                <a href="<?php echo $_product->link ?>"
                                   title="<?php echo $_product->title; ?>"
                                    <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                    >
                                    <img src="<?php echo $_product->_image; ?>"
                                         title="<?php echo $_product->title; ?>"
                                         alt="<?php echo $_product->title; ?>"
                                        >
                                </a>
                            </div>
                        <?php }?>

                        <!-- Begin bs-content -->
                        <?php  ?>
						<div class="box-info">

                            <?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
                                <h2 class="product name product-item-name product-name">
                                    <a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                        >
                                        <?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
                                    </a>
                                </h2>
                            <?php } ?>
							
							<?php if ($this->_getConfig('product_source') != 'media') { ?>
							
								<?php if ((int)$this->_getConfig('product_reviews_count', 1)) {
										$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
										echo $block->getReviewsSummaryHtml($_product,$templateType,true); 
								} ?>
								
								<?php if ((int)$this->_getConfig('product_sku_display', 1)) { ?>
										<div class="ellipsis1Line">
											<span>SKU # <?php /* @escapeNotVerified */ echo $_product->getData('sku') ?></span>
										</div>
								<?php } ?>

                                <?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
									<div class="art-case-quantity ellipsis1Line">
										<?php echo $this->getProductPrice($_product); ?>
										<div class="price-box">
											<span class="price"> | </span>
											<span>
											<?php /* @escapeNotVerified */ echo $_product->getData('ars_case_quantity') ?> </span>
										</div>
									</div>
								<?php } ?>
									  
								<div class="art-cart-button bottom-action">
									<div class="actions-primary">
										 <?php if ($_product->isSaleable()): ?>
											<?php $postParams = $this->getAddToCartPostParams($_product); 
											$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
											$session = $objectManager->get('\Magento\Framework\View\Element\FormKey');
											?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo \Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][\Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<input  name="form_key" type="hidden" value="<?php echo $session->getFormKey(); ?>" />
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart primary btn-action btn-cart">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()){ ?>
										<a href="#" data-post='<?php  echo $block->getAddToWishlistParams($_product); ?>'  class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist" title="<?php  echo __('Add to Wish List') ?>">
											<span><?php  echo __('Add to Wish List') ?></span>
										</a>
									<?php } ?>
								</div>
								
							<?php } ?>
							
                            <?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->_description) != '') { ?>
                                <div class="bs-description">
                                    <?php echo $_product->_description; ?>
                                </div>
                            <?php } ?>
							
                            <?php if ($this->_getConfig('cat_title_display') == 1 && $this->_getConfig('product_source') != 'media') { ?>
                               <div class="bs-category"><?php echo __('Category:&nbsp') ;?>
									<a  href="<?php echo $_product->cat_link; ?>"  title="<?php echo $_product->cat_title; ?>"  <?php echo $helper->parseTarget($this->_getConfig('target')); ?>>
										 <?php echo  $helper->truncate($_product->cat_title, $this->_getConfig('category_title_max_characs', 25)); ?>
									</a>
									
                                </div>
                            <?php } ?>

                            <?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
                                <div class="bs-detail">
                                    <a href="<?php echo $_product->link ?>"
                                       title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                        >
                                        <?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
                                    </a>
                                </div>
                            <?php } ?>

                        </div>
						
                        <!-- End bs-content -->
                    </div>
                    <!-- End bs-item-inner -->
                </div><!-- End bs-item-cf -->
            <?php } ?>
			</div>
        </div>
        <!-- End bs-items -->
    </div><!-- End Sm-basic-products -->
   <?php if ($this->_getConfig('posttext') != null) { ?>
		<div class="bs-posttext">
			<?php echo $this->_getConfig('posttext'); ?>
		</div>
	<?php } ?>
<?php
} else {
	echo '<h1 style="color:#f1703d;">Has no content to show!</h1>';
}
?>