<?php
/*------------------------------------------------------------------------
# SM Mega Menu - Version 3.1.0
# Copyright (c) 2015 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
namespace Sm\MegaMenu\Setup;

use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

class InstallData implements InstallDataInterface
{
	/**
	 * {@inheritdoc}
	 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
	 */
	public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
	{
		$groups = [
			['Mega Menu Demo 1', 1, 'This is mega menu demo']
		];

		/*
		 * Way 1
		 * */
		$columns = ['title', 'status', 'content'];
		$setup->getConnection()->insertArray($setup->getTable('sm_megamenu_groups'), $columns, $groups);

		$items = [
			[
				'group_id' => 1,
				'title' => 'Root[Mega Menu Demo 1]',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 0,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 0,
				'data_type' => '',
				'content' => '',
				'priorities' => 0,
				'depth' => 0,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'All Mega Menu',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 1,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => 'sm/megamenu/images/new-icon-h.png',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 1,
				'depth' => 1,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 2,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 2,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 2,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 2',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 2,
				'order_item' => 3,
				'position_item' => 2,
				'cols_nb' => 2,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 3,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 3',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 2,
				'order_item' => 4,
				'position_item' => 2,
				'cols_nb' => 2,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 4,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 4',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 2,
				'order_item' => 5,
				'position_item' => 2,
				'cols_nb' => 4,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 5,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 5',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 2,
				'order_item' => 6,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 6,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 6',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 2,
				'order_item' => 7,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 7,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Add Contents Video',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 3,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'add_content_video',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 8,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Video 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 3,
				'order_item' => 9,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="video_megamenu" style=""><iframe src="http://player.vimeo.com/video/41286259?title=0&amp;byline=0&amp;portrait=0" id="fitvid402488"></iframe></div>',
				'priorities' => 9,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Add Media Elements',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 4,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'add_media_element',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 10,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Media Element 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 4,
				'order_item' => 11,
				'position_item' => 1,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="media_elements">      <div class="media_detail1">              <ul class="media-list">                                            <li class="media"><a href="#" class="pull-right"><img src="{{media url="sm/megamenu/images/01_menu.jpg"}}" alt="" width="70" class="img-thumbnail media-object"></a>                                                <div class="media-body">                                                    <p>Lorem Ipsum beschikbaar heeft te lijden gehad van wijzigingen in een of andere vorm, door ingevoegde</p>                                                </div>                                            </li>                                            <li class="media"><a href="#" class="pull-right"><img src="{{media url="sm/megamenu/images/02_menu.jpg"}}" alt="" width="70" class="img-thumbnail media-object"></a>                                                <div class="media-body">                                                    <p>Er zijn vele variaties van passages maar van in een of andere vorm, door ingevoegde humor of willekeu seloofwaardig ogen.</p>                                                </div>                                            </li>                                        </ul>       </div></div>',
				'priorities' => 11,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Add Google Map',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 5,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'add_google_map',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 12,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Google Map',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 5,
				'order_item' => 13,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="google_map_1"><script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script><div style="overflow:hidden;height:202px;width:370px;"><div id="gmap_canvas" style="height:202px;width:370px;"></div><a class="google-map-code" href="http://www.themecircle.net" id="get-map-data">themecircle</a></div><script type="text/javascript"> function init_map(){var myOptions = {zoom:16,center:new google.maps.LatLng(21.0277644,105.83415979999995),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(21.0277644, 105.83415979999995)});infowindow = new google.maps.InfoWindow({content:"<b>Ha Noi</b><br/>Thai Ha Street<br/> Ha Noi City" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window,"load", init_map);</script></div>',
				'priorities' => 13,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Text 1',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 6,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'text_1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 14,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Element Text 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 6,
				'order_item' => 15,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="element_text_1"><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged, ...</p></div>',
				'priorities' => 15,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Text 2',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 7,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'text_2',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 16,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Element Text 2',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 7,
				'order_item' => 17,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="element_text_2"><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, ...</p></div>',
				'priorities' => 17,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Text 3',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 8,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'text_3',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 18,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Element Text 3',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 8,
				'order_item' => 19,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="element_text_1"><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry`s standard dummy text ever since the 1500s, ...</p></div>',
				'priorities' => 19,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Features',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 1,
				'order_item' => 2,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'features',
				'icon_url' => 'sm/megamenu/images/feature-icon-h.png',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="megamenu-dropdown"><ul class="item-home-megamenu layout"><li class="title-megamenu-home">Layouts</li><li><a title="Layout 1" href="#">Layout 1</a></li><li><a title="Layout 2" href="#">Layout 2</a></li><li><a title="Layout 3" href="#">Layout 3</a></li>                <li><a title="Layout 4" href="#">Layout 4</a></li>                <li><a title="Layout 5" href="#">Layout 5</a></li>                <li><a title="Layout 6" href="#">Layout 6</a></li></ul> <ul class="item-home-megamenu color"><li class="title-megamenu-home">Color Styles</li><li class="pink"><a title="Pink" href="#"><img src="{{media url="sm/megamenu/images/color/pink.png"}}" alt="Pink" />Pink</a></li>                <li class="orange"><a title="Orange" href="#"><img src="{{media url="sm/megamenu/images/color/orange.png"}}" alt="Orange" />Orange</a></li>                <li class="purple"><a title="Purple" href="#"><img src="{{media url="sm/megamenu/images/color/purple.png"}}" alt="Purple" />Purple</a></li>                 <li class="red"><a title="Red" href="#"><img src="{{media url="sm/megamenu/images/color/red.png"}}" alt="Red" />Red</a></li>                <li class="royal-blue"><a title="Royal Blue" href="#"><img src="{{media url="sm/megamenu/images/color/royal-blue.png"}}" alt="Royal Blue" />Royal Blue</a></li>                <li class="salmon"><a title="Salmon" href="#"><img src="{{media url="sm/megamenu/images/color/salmon.png"}}" alt="Salmon" />Salmon</a></li>                <li class="silver"><a title="Silver" href="#"><img src="{{media url="sm/megamenu/images/color/silver.png"}}" alt="Silver" />Silver</a></li>               <li class="taupe"><a title="Taupe" href="#"><img src="{{media url="sm/megamenu/images/color/taupe.png"}}" alt="Taupe" />Taupe</a></li>               <li class="white"><a title="White" href="#"><img src="{{media url="sm/megamenu/images/color/white.png"}}" alt="White" />White</a></li>               <li class="yellow"><a title="Yellow" href="#"><img src="{{media url="sm/megamenu/images/color/yellow.png"}}" alt="Yellow" />Yellow</a></li></ul><ul class="item-home-megamenu header"><li class="title-megamenu-home">Headers</li><li><a title="Header Type 1" href="#">Header Type 1</a></li><li><a title="Header Type 2" href="#">Header Type 2</a></li><li><a title="Header Type 3" href="#">Header Type 3</a></li></ul><ul class="item-home-megamenu detail"><li class="title-megamenu-home">Product Detail Layouts</li><li><a title="Product Detail - Full" href="#">Product Detail - Full</a></li><li><a title="Product Detail - Left Sidebar" href="#">Product Detail - Left Sidebar</a></li><li><a title="Product Detail - Right Sidebar" href="#">Product Detail - Right Sidebar</a></li><li><a title="Thumbnail  - Vertical" href="#">Thumbnail  - Vertical</a></li><li><a title="Thumbnail - Horizontal" href="#">Thumbnail - Horizontal</a></li></ul><ul class="item-home-megamenu detail"><li class="title-megamenu-home">Zoom Types</li><li><a title="Product Page Inner Zoom" href="#">Product Page Inner Zoom</a></li><li><a title="Product Page Outer Zoom" href="#">Product Page Outer Zoom</a></li><li><a title="Product Page Lens Zoom" href="#">Product Page Lens Zoom</a></li></ul><div style="clear:both;"></div><ul class="item-home-megamenu layout"><li class="title-megamenu-home">Listing Layouts</li><li><a title="Without Sidebar" href="#">Without Sidebar</a></li><li><a title="Left Sidebar" href="#">Left Sidebar</a></li><li><a title="Right Sidebar" href="#">Right Sidebar</a></li><li><a title="Left - Right Sidebar" href="#">Left - Right Sidebar</a></li><li><a title="2 Columns Products" href="#">2 Columns Products</a></li><li><a title="3 Columns Products" href="#">3 Columns Products</a></li><li><a title="4 Columns Products" href="#">4 Columns Products</a></li><li><a title="5 Columns Products" href="#">5 Columns Products</a></li><li><a title="6 Columns Products" href="#">6 Columns Products</a></li></ul><ul class="item-home-megamenu layout"><li class="title-megamenu-home">About Us Layouts</li><li><a title="About Us Style 1" href="#">About Us Style 1</a></li><li><a title="About Us Style 2" href="#">About Us Style 2</a></li><li><a title="About Us Style 3" href="#">About Us Style 3</a></li><li><a title="About Us Style 4" href="#">About Us Style 4</a></li></ul><ul class="item-home-megamenu layout"><li class="title-megamenu-home">Contact Us Layouts</li><li><a title="Contact Us Style 1" href="#">Contact Us Style 1</a></li><li><a title="Contact Us Style 2" href="#">Contact Us Style 2</a></li><li><a title="Contact Us Style 3" href="#">Contact Us Style 3</a></li><li><a title="Contact Us Style 4" href="#">Contact Us Style 4</a></li></ul><ul class="item-home-megamenu layout"><li class="title-megamenu-home">404 Page Layout</li><li><a title="404 Page Style 1" href="#">404 Page Style 1</a></li></ul><ul class="item-home-megamenu detail"><li class="title-megamenu-home">Effect Hover Product</li><li><a title="Simple" href="#">Simple</a></li><li><a title="Display Second Image" href="#">Display Second Image</a></li><li><a title="Display Slider Image" href="#">Display Slider Image</a></li></ul></div>',
				'priorities' => 20,
				'depth' => 1,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'All Category',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 1,
				'order_item' => 21,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => 'sm/megamenu/images/all-category.png',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 21,
				'depth' => 1,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 22,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 22,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 2',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 22,
				'order_item' => 23,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 23,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 3',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 22,
				'order_item' => 24,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 24,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 4',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 22,
				'order_item' => 25,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 25,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 5',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 22,
				'order_item' => 26,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 26,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 6',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 22,
				'order_item' => 27,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 27,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Women',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 23,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/4',
				'content' => '',
				'priorities' => 28,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'New Arrivals',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short desciption',
				'align' => 1,
				'parent_id' => 29,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/10',
				'content' => '',
				'priorities' => 29,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Tops & Blouses',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short desciption',
				'align' => 1,
				'parent_id' => 29,
				'order_item' => 30,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/11',
				'content' => '',
				'priorities' => 30,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Pants & Denim',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short desciption',
				'align' => 1,
				'parent_id' => 29,
				'order_item' => 31,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/12',
				'content' => '',
				'priorities' => 31,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Dresses & Skirts',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short desciption',
				'align' => 1,
				'parent_id' => 29,
				'order_item' => 32,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/13',
				'content' => '',
				'priorities' => 32,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Men',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 24,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/5',
				'content' => '',
				'priorities' => 33,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'New Arrivals',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 34,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/14',

				'content' => '',
				'priorities' => 34,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Shirts',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 34,
				'order_item' => 35,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/15',
				'content' => '',
				'priorities' => 35,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Tees, Knits and Polos',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 34,
				'order_item' => 36,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/16',
				'content' => '',
				'priorities' => 36,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Pants & Denim',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 34,
				'order_item' => 37,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/17',
				'content' => '',
				'priorities' => 37,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Blazers',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 34,
				'order_item' => 38,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/40',
				'content' => '',
				'priorities' => 38,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Accessories',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 25,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/6',
				'content' => '',
				'priorities' => 39,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Eyewear',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 40,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/18',
				'content' => '',
				'priorities' => 40,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Jewelry',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 40,
				'order_item' => 41,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/19',
				'content' => '',
				'priorities' => 41,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Shoes',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 40,
				'order_item' => 42,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/20',
				'content' => '',
				'priorities' => 42,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Bags & Luggage',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 40,
				'order_item' => 43,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/21',
				'content' => '',
				'priorities' => 43,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Home & Decor',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 26,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/7',
				'content' => '',
				'priorities' => 44,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Books & Music',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 45,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/22',
				'content' => '',
				'priorities' => 45,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Bed & Bath',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 45,
				'order_item' => 46,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/23',
				'content' => '',
				'priorities' => 46,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Electronics',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 45,
				'order_item' => 47,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/24',
				'content' => '',
				'priorities' => 47,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Decorative Accents',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 45,
				'order_item' => 48,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/25',
				'content' => '',
				'priorities' => 48,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Sale',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 27,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/8',
				'content' => '',
				'priorities' => 49,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Women',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 50,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/26',
				'content' => '',
				'priorities' => 50,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Men',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 50,
				'order_item' => 51,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/27',
				'content' => '',
				'priorities' => 51,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Accessories',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 50,
				'order_item' => 52,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/28',
				'content' => '',
				'priorities' => 52,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Home & Decor',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 50,
				'order_item' => 53,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/29',
				'content' => '',
				'priorities' => 53,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'VIP',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 28,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 4,
				'data_type' => 'category/9',
				'content' => '',
				'priorities' => 54,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Beauty & Health',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 55,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 55,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Mind & Body',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 55,
				'order_item' => 56,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 56,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Yoga & Pilates',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 55,
				'order_item' => 57,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 57,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Hair & Makeup',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 55,
				'order_item' => 58,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 58,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Lose Weight',
				'status' => 1,
				'show_title' => 1,
				'description' => 'a short description',
				'align' => 1,
				'parent_id' => 55,
				'order_item' => 59,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 59,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => 0,
				'show_sub_category' => 1,
				'limit_sub_category' => 0
			],
			[
				'group_id' => 1,
				'title' => 'Best Seller',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 1,
				'order_item' => 22,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => 'sm/megamenu/images/hot-icon-h.png',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 60,
				'depth' => 1,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 61,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 61,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 2',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 61,
				'order_item' => 62,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 62,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 3',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 61,
				'order_item' => 63,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 63,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 4',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 61,
				'order_item' => 64,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 64,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 5',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 61,
				'order_item' => 65,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 65,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 6',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 61,
				'order_item' => 66,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 66,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Static Men',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 62,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="static-category">     <div class="image-cat-st">          <a title="Men" href="#"><img src="{{media url="sm/megamenu/images/men-image-menu.jpg"}}" alt="Men" /></a>     </div>     <div class="title-cat-st">          <h2><a title="Men" href="#">Men</a></h2>     </div>     <div class="des-cat-st">         <p>Veritatis officia expedita excepteur labore etiam leo class</p>     </div></div>',
				'priorities' => 67,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Static Women',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 63,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="static-category"><div class="image-cat-st"><a title="Women & Accessories" href="#"><img src="{{media url="sm/megamenu/images/women-image-menu.jpg"}}" alt="Women & Accessories" /></a></div><div class="title-cat-st"><h2><a title="Women & Accessories" href="#">Women & Accessories</a></h2></div><div class="des-cat-st"><p>Morbi laboriosam recusandae iure</p></div></div>',
				'priorities' => 68,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Static Out Door & Sports',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 64,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="static-category"><div class="image-cat-st"><a title="Out Door & Sports" href="#"><img src="{{media url="sm/megamenu/images/sport-image-menu.jpg"}}" alt="Out Door & Sports" /></a></div><div class="title-cat-st"><h2><a title="Out Door & Sports" href="#">Out Door & Sports</a></h2></div><div class="des-cat-st"><p>Veritatis officia expedita excepteur labore etiam leo class</p></div></div>',
				'priorities' => 69,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Health Care Devices',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 65,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="static-category"><div class="image-cat-st"><a title="Health Care Devices" href="#"><img src="{{media url="sm/megamenu/images/health-image-menu.jpg"}}" alt="Health Care Devices" /></a></div><div class="title-cat-st"><h2><a title="Health Care Devices" href="#">Health Care Devices</a></h2></div><div class="des-cat-st"><p>Phasellus semper quaerat nullam vulputate phasellus augue modi</p></div></div>',
				'priorities' => 70,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Home & Kitchen',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 66,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="static-category"><div class="image-cat-st"><a title="Home & Kitchen" href="#"><img src="{{media url="sm/megamenu/images/home-kitchen-image-menu.jpg"}}" alt="Home & Kitchen" /></a></div><div class="title-cat-st"><h2><a title="Home & Kitchen" href="#">Home & Kitchen</a></h2></div><div class="des-cat-st"><p>Semper quaerat nullam vulputate phasellus augue modi</p></div></div>',
				'priorities' => 71,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Fishing',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 67,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="static-category"><div class="image-cat-st"><a title="Fishing" href="#"><img src="{{media url="sm/megamenu/images/fishing-image-menu.jpg"}}" alt="Fishing" /></a></div><div class="title-cat-st"><h2><a title="Fishing" href="#">Fishing</a></h2></div><div class="des-cat-st"><p>Phasellus semper quaerat nullam vulputate phasellus augue modi</p></div></div>',
				'priorities' => 72,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Flyout',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 1,
				'order_item' => 61,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 73,
				'depth' => 1,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 74,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 74,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'ThemeForest',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 75,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 75,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'GraphicRiver',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 75,
				'order_item' => 76,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 76,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'EnvatoSites',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 75,
				'order_item' => 77,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'envato_sites',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 77,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 78,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'envato_col_1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 78,
				'depth' => 4,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],

			[
				'group_id' => 1,
				'title' => 'Tuts+',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 79,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'envato_tuts',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="envato-sublv-3"><ul><li class="psd-tuts">PSD Tuts</li><li class="code-tuts">CODE Tuts</li></ul></div>',
				'priorities' => 79,
				'depth' => 5,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'We are Envato',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 79,
				'order_item' => 80,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'envato_wae',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 80,
				'depth' => 5,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Support Center',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 79,
				'order_item' => 81,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => 'envato_supcen',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 81,
				'depth' => 5,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'PhotoDune',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 75,
				'order_item' => 78,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 82,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Creattica',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 75,
				'order_item' => 83,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 83,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'MicroLancer',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 75,
				'order_item' => 84,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 84,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'ActiveDen',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 75,
				'order_item' => 85,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 85,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Grid',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 1,
				'order_item' => 74,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 86,
				'depth' => 1,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 1',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 87,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 87,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 2',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 87,
				'order_item' => 88,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 88,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 3',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 87,
				'order_item' => 89,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 89,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 4',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 87,
				'order_item' => 90,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 90,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 5',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 87,
				'order_item' => 91,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 91,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 6',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 87,
				'order_item' => 92,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 92,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Column 7',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 1,
				'parent_id' => 87,
				'order_item' => 93,
				'position_item' => 2,
				'cols_nb' => 6,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 93,
				'depth' => 2,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '1 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 88,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => 'col-sm-1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 94,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '5 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 88,
				'order_item' => 95,
				'position_item' => 2,
				'cols_nb' => 5,
				'custom_class' => 'col-sm-5',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 95,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '2 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 89,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 2,
				'custom_class' => 'col-sm-2',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 96,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '4 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 89,
				'order_item' => 97,
				'position_item' => 2,
				'cols_nb' => 4,
				'custom_class' => 'col-sm-4',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 97,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '3 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 90,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 3,
				'custom_class' => 'col-sm-3',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 98,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '3 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 90,
				'order_item' => 99,
				'position_item' => 2,
				'cols_nb' => 3,
				'custom_class' => 'col-sm-3',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 99,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '4 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 91,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 4,
				'custom_class' => 'col-sm-4',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 100,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '2 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 91,
				'order_item' => 101,
				'position_item' => 2,
				'cols_nb' => 2,
				'custom_class' => 'col-sm-2',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 101,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '5 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 92,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 5,
				'custom_class' => 'col-sm-5',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 102,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '1 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 92,
				'order_item' => 103,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => 'col-sm-1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 103,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '2 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 93,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 2,
				'custom_class' => 'col-sm-2',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 104,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '2 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 93,
				'order_item' => 105,
				'position_item' => 2,
				'cols_nb' => 2,
				'custom_class' => 'col-sm-2',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 105,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '2 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 93,
				'order_item' => 106,
				'position_item' => 2,
				'cols_nb' => 2,
				'custom_class' => 'col-sm-2',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 106,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '1 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 94,
				'order_item' => 0,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => 'col-sm-1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 107,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '1 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 94,
				'order_item' => 108,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => 'col-sm-1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 108,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '1 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 94,
				'order_item' => 109,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => 'col-sm-1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 109,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '1 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 94,
				'order_item' => 110,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => 'col-sm-1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 110,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '1 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 94,
				'order_item' => 111,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => 'col-sm-1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 111,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => '1 column',
				'status' => 1,
				'show_title' => 1,
				'description' => '',
				'align' => 1,
				'parent_id' => 94,
				'order_item' => 112,
				'position_item' => 2,
				'cols_nb' => 1,
				'custom_class' => 'col-sm-1',
				'icon_url' => '',
				'target' => 3,
				'type' => 1,
				'data_type' => '',
				'content' => '',
				'priorities' => 112,
				'depth' => 3,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Contact Form',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 2,
				'parent_id' => 1,
				'order_item' => 87,
				'position_item' => 2,
				'cols_nb' => 3,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<ul class="dropdown-menu">
                            <li>
                                <form id="contact1" action="#" name="contactform" method="post">
                                    <div class="field_input contact_field-1">
                                        <input type="text" name="name" id="name1" class="form-control" placeholder="Name">
                                        <input type="text" name="email" id="email1" class="form-control" placeholder="Email">
                                    </div>
                                    <div class="field_input contact_field-2">
                                        <input type="text" name="phone" id="phone1" class="form-control" placeholder="Phone">
                                        <input type="text" name="subject" id="subject1" class="form-control" placeholder="Subject">
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="field_input contact_field-3">
                                        <textarea class="form-control" name="comments" id="comments1" rows="6" placeholder="Your Message ..."></textarea>
                                    </div>
                                    <div class="field_input contact_field-4">
                                        <div class="pull-right-contact send">
                                            <input type="submit" value="SEND" id="submit1" class="btn btn-primary small">
                                        </div>
                                    </div>
                                </form>
                            </li>
                        </ul>',
				'priorities' => 113,
				'depth' => 1,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			],
			[
				'group_id' => 1,
				'title' => 'Shop By Product',
				'status' => 1,
				'show_title' => 2,
				'description' => '',
				'align' => 2,
				'parent_id' => 1,
				'order_item' => 114,
				'position_item' => 2,
				'cols_nb' => 3,
				'custom_class' => '',
				'icon_url' => '',
				'target' => 3,
				'type' => 7,
				'data_type' => '',
				'content' => '<div class="megamenu-dropdown-2">
<ul class="item-home-megamenu icon">
<li><a title="Desktop Icon" href="#"><i class="fa fa-desktop"></i>Desktop Icon</a></li>
<li><a title="Laptop Icon" href="#"><i class="fa fa-laptop"></i>Laptop Icon</a></li>
<li><a title="Tablet Icon" href="#"><i class="fa fa-tablet"></i>Tablet Icon</a></li>
<li><a title="Mobile Icon" href="#"><i class="fa fa-mobile"></i>Mobile Icon</a></li>
<li><a title="Android Icon" href="#"><i class="fa fa-android"></i>Android Icon</a></li>
<li><a title="Apple Icon" href="#"><i class="fa fa-apple"></i>Apple Icon</a></li>
<li><a title="Windows Icon" href="#"><i class="fa fa-windows"></i>Windows Icon</a></li>
<li><a title="Linux Icon" href="#"><i class="fa fa-linux"></i>Linux Icon</a></li>
</ul>
<ul class="item-home-megamenu icon"><li>
<a title="Leaf Icon" href="#"><i class="fa fa-leaf"></i>Leaf Icon</a></li>
<li><a title="Hear Icon" href="#"><i class="fa fa-heart-o"></i>Hear Icon</a></li>
<li><a title="Sun Icon" href="#"><i class="fa fa-sun-o"></i>Sun Icon</a></li>
<li><a title="Moon Icon" href="#"><i class="fa fa-moon-o"></i>Moon Icon</a></li>
<li><a title="Camera Icon" href="#"><i class="fa fa-camera-retro"></i>Camera Icon</a></li>
<li><a title="Bars Icon" href="#"><i class="fa fa-bars"></i>Bars Icon</a></li>
<li><a title="Pagelines Icon" href="#"><i class="fa fa-pagelines"></i>Pagelines Icon</a></li>
<li><a title="Ambulance Icon" href="#"><i class="fa fa-ambulance"></i>Ambulance Icon</a></li>
</ul>
<ul class="item-home-megamenu icon">
<li><a title="Beer Icon" href="#"><i class="fa fa-beer"></i>Beer Icon</a></li>
<li><a title="Code Icon" href="#"><i class="fa fa-code"></i>Code Icon</a></li>
<li><a title="Envelope Icon" href="#"><i class="fa fa-envelope-o"></i>Envelope Icon</a></li>
<li><a title="Bitbucket Icon" href="#"><i class="fa fa-bitbucket-square"></i>Bitbucket Icon</a></li>
<li><a title="Globe Icon" href="#"><i class="fa fa-globe"></i>Globe Icon</a></li>
<li><a title="Skype Icon" href="#"><i class="fa fa-skype"></i>Skype Icon</a></li>
<li><a title="Github Icon" href="#"><i class="fa fa-github"></i>Github Icon</a></li>
<li><a title="Renren Icon" href="#"><i class="fa fa-renren"></i>Renren Icon</a></li>
</ul>
<div class="clear_item_megamenu"></div>
<div class="element_shop_product-1"><p>Font Awesome gives you scalable vector icons that can instantly be customized — size, color, drop shadow, and anything that can be done with the power of CSS.</p></div>
<div class="element_shop_product-2"><p>Font Awesome font licensed under <a href="http://scripts.sil.org/OFL">SIL OFL 1.1</a> Code licensed under <a href="http://opensource.org/licenses/mit-license.html">MIT License</a> Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a></p></div>
</div>',
				'priorities' => 114,
				'depth' => 1,
				'show_image_product' => 2,
				'show_title_product' => 2,
				'show_rating_product' => 2,
				'show_price_product' => 2,
				'show_title_category' => 2,
				'limit_category' => '',
				'show_sub_category' => 1,
				'limit_sub_category' => ''
			]
		];

		/*
		 * Way 2
		 * */
		foreach($items as $item)
		{
			$setup->getConnection()->insert($setup->getTable('sm_megamenu_items'), $item);
		}
	}
}