<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config = $this->helper('Sm\Market\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<div class="toolbar-top">
    <?php echo $block->getToolbarHtml() ?>
	</div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
		$showReview = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
		$showReview = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-product products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
		
		<?php if($viewMode == 'grid'){ ?>
		
        <ol class="art-product-list products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
					<div class="product-item-info" data-container="product-grid">
						<div class="item-inner">
							<div class="box-image">
								<!--2017/11/13 Tenzin: Display Best Seller Badge -->
								<?php
								$enable_best_seller = $_product->getAttributeText('ars_best_seller') === "Yes" ? TRUE:FALSE;
								if($enable_best_seller) { ?>
									<div class="art-best-seller-icon-row">
										<span class="art-best-seller-icon-container">
											<span class="art-best-seller-icon-label">
												<?php /* @escapeNotVerified */ echo $_product->getResource()->getAttribute('ars_best_seller')->getStoreLabel() ?>
											</span>
										</span>
									</div>
								<?php } ?>
								<?php $productImage = $block->getImage($_product, $image);?>
								
								<!--LABEL PRODUCT-->

									<?php
										$specialprice = $_product->getSpecialPrice();
										$specialPriceFromDate = $_product->getSpecialFromDate();
										$specialPriceToDate = $_product->getSpecialToDate();
										
										$today = time();

										if ($specialprice && $_config->getAdvanced('show_salelabel')) {
											if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
												<div class="label-product label-sale">
													<span class="sale-product-icon">
														<?php echo __('Sale'); ?>
													</span>
												</div>
											<?php }
										}
									?>
									
									<?php
									$now = date("Y-m-d");
									$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
									$newsTo = substr($_product->getNewsToDate(), 0, 10);
									
									
									if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
												<div class="label-product label-new">
													<span class="new-product-icon"><?php echo __('New'); ?></span>
												</div>
										<?php }
									} ?>
									
									
								<!--END LABEL PRODUCT-->

								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php echo $productImage->toHtml(); ?>
								</a>
							</div>
							
							<div class="product details product-item-details box-info">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<h2 class="product name product-item-name product-name">
									<a class="clamped ellipsis2Line product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h2>
								<!-- 2017/11/13 Tenzin: Add icons per product -->
								<?php
								//https://magento.stackexchange.com/questions/132098/magento-2-how-to-display-custom-attribute-in-catalog
								//Attributes must be configured to Yes for "Use in Product Listing"
								$enable_custom_packaging = $_product->getAttributeText('ars_custom_packaging') === "Yes" ? TRUE:FALSE;
								$enable_ready_to_assemble = $_product->getAttributeText('ars_ready_to_assemble') === "Yes" ? TRUE:FALSE;
								$enable_product_question = $_product->getAttributeText('ars_product_question') === "Yes" ? TRUE:FALSE;
								//Next two attributes returns string of all values joined by commas
								$enable_packaging_recyclable = $_product->getResource()->getAttribute('ars_packaging_recyclable')->getFrontend()->getValue($_product);
								$enable_shipping_icon = $_product->getResource()->getAttribute('ars_shipping_type')->getFrontend()->getValue($_product);
								//Combining Packaging Recyclable and Shipment Type values to only loop through once
								$enable_packaging_shipping = $enable_packaging_recyclable . ',' . $enable_shipping_icon;
								//Checking if any of the icons are enabled
								if($enable_ready_to_assemble || $enable_product_question || !empty($enable_packaging_shipping) ) { ?>
								<div class="art-description-icons">
								<?php if($enable_ready_to_assemble) { ?>
										<img class="art-ready-to-assemble" title="This item will come disassembled and needs to be put together by you!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Display_Case_Icon_Red.png" />
								<?php } ?>
								<?php if($enable_product_question) { ?>
										<img class="art-product-question" title="Have any question about this item? Click here to request help!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/IT_Consulting_Icon_Yellow.png" />
								<?php } ?>
								<?php if(!empty($enable_packaging_shipping)) {
									//convert list of values into array
									//remove any white space in front and end of each value
									$enable_packaging_shipping_array = array_map('trim', explode( ',', $enable_packaging_shipping ));
									foreach($enable_packaging_shipping_array as $type) {
										if($type === "24 Hours") { ?>
											<img class="art-shipping-24hours" title="It will take, at most, 24 Hours to ship this product." src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/shipping-24.png" />
										<?php } elseif($type === "LTL Shipment") { ?>
											<img class="art-ltl-freight" title="This item requires LTL Freight instead of Ground." src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/General_Store_Operations_Icon_Red.png" />
										<?php } elseif($type === "40% Recycled") { ?>
											<img class="art-packaging-recycled" title="This item is made of 40% recycled material!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Shopping_Bag_Icon_Green.png" />
										<?php } elseif($type === "Reusable") { ?>
											<img class="art-packaging-reusable" title="This item can be used more than once!" src="https://arsimages.azurewebsites.net/ars_files/images/wysiwyg/icon/Label_Sticker_Icon_1_Green.png" />
										<?php } ?>
									<?php } ?>
								<?php } ?>
								</div>
								<?php } ?>
								
								<?php if ($showReview):?>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
								<?php endif; ?>
								
								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								<?php echo $block->getProductDetailsHtml($_product); ?>
								
								<div class="product-item-inner">
									<?php if ($showDescription):?>
										<div class="art-catalog-listing-description ellipsis1Line product description product-item-description">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										</div>
									<?php endif; ?>
								</div>
								
								<div class="bottom-action">
									<?php if($enable_custom_packaging) { ?>
										<a href="/custom-shopping-bags/?product-name=<?php /* @escapeNotVerified */ echo htmlspecialchars($_helper->productAttribute($_product, $_product->getName(), 'name'));?>&custom-packaging-sku=<?php /* @escapeNotVerified */ echo $_product->getData('sku')?>&dimensions=<?php /* @escapeNotVerified */ echo htmlspecialchars($_product->getResource()->getAttribute('ars_dims')->getFrontend()->getValue($_product))?>">
											<button title="Custom Packaging" class="art-custom-button primary btn-action ellipsis1Line clamped"><span>Customize this Item</span></button>
										</a>
									<?php } ?>
									<?php if($_config->getAdvanced('show_addtocart_button')){?>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart primary btn-action btn-cart">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									<?php } ?>
									
									<?php if($_config->getAdvanced('show_wishlist_button')){?>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist"  role="button">
												<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
											</a>
										<?php endif; ?>
									<?php } ?>
									
									<?php if($_config->getAdvanced('show_compare_button')){?>
										<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
										<a href="#"  class="action tocompare btn-action link-compare"  title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
											<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
										</a>
									<?php } ?>
								</div>
								<span class="art-product-listing-sku">SKU: <?php /* @escapeNotVerified */ echo $_product->getData('sku') ?></span>
							</div>
						</div>
					</div>
                </li>
            <?php endforeach; ?>
        </ol>
		
		<?php } else {?>
			<ol class="products list items product-items">
				<?php foreach ($_productCollection as $_product): ?>
					<li class="item respl-item-list product product-item">
						<div class="product-item-info" data-container="product-grid">
							<div class="item-inner">
								<div class="box-image-list">
									<?php $productImage = $block->getImage($_product, $image); ?>
									
									<!--LABEL PRODUCT-->

										<?php
											$specialprice = $_product->getSpecialPrice();
											$specialPriceFromDate = $_product->getSpecialFromDate();
											$specialPriceToDate = $_product->getSpecialToDate();
											
											$today = time();

											if ($specialprice && $_config->getAdvanced('show_salelabel')) {
												if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
													<div class="label-product label-sale">
														<span class="sale-product-icon">
															<?php echo __('Sale'); ?>
														</span>
													</div>
												<?php }
											}
										?>
										
										<?php
										$now = date("Y-m-d");
										$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
										$newsTo = substr($_product->getNewsToDate(), 0, 10);
										
										
										if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
											if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
													<div class="label-product label-new">
														<span class="new-product-icon"><?php echo __('New'); ?></span>
													</div>
											<?php }
										} ?>
										
										
									<!--END LABEL PRODUCT-->

									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<?php echo $productImage->toHtml(); ?>
									</a>

								</div>
								
								<div class="product details product-item-details box-info-list">
									<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
									<h2 class="product name product-item-name product-name">
										<a class="clamped ellipsis2Line product-item-link" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h2>
									<span>SKU # <?php /* @escapeNotVerified */ echo $_product->getData('sku') ?></span>
								
									<?php if ($showReview):?>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
									<?php endif; ?>
									
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<?php echo $block->getProductDetailsHtml($_product); ?>
									
									<div class="product-item-inner">
										<?php if ($showDescription):?>
											<div class="art-catalog-listing-description ellipsis1Line product description product-item-description">
												<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
												   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
											</div>
										<?php endif; ?>
									</div>
									
									<div class="bottom-action">
										<?php if($_config->getAdvanced('show_addtocart_button')){?>
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart btn-action btn-cart">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										<?php } ?>
										
										<div class="add-to-links" data-role="add-to-links" class="actions-secondary">
											<?php if($_config->getAdvanced('show_wishlist_button')){?>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
													<a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist"  role="button">
														<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
													</a>
												<?php endif; ?>
											<?php } ?>
											
											<?php if($_config->getAdvanced('show_compare_button')){?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
												<a href="#"  class="action tocompare btn-action link-compare"  title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
													<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
												</a>
											<?php } ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			</ol>
		<?php } ?>
    </div>
	<div class="toolbar-bottom">
    <?php echo $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
